### ISSUE TITLE
关于在Linux下的兼容问题

### ISSUE THREAD

**Issue by you9you** [theme-shoka-x/hexo-theme-shokaX#106]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

- 在运行`npx SXC install shokaX`的时候抛出`/usr/bin/env: "node\r": 没有那个文件或目录`
- 在运行`npx hexo server`并访问4000端口的时候抛出`WARN  No layout: index.html`

### 复现步骤

> 在运行`npx SXC install shokaX`的时候抛出`/usr/bin/env: "node\r": 没有那个文件或目录`

已尝试通过VSCode将`node_modules/.bin/SXC`从 CRLF 改为 LF，可以解决

> 在运行`npx hexo server`并访问4000端口的时候抛出`WARN  No layout: index.html`

可能是Linux路径区分大小写的问题，但通过更改文件名未解决

### 相关配置

node: v16.17.1

```json
{
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "add": "^2.0.6",
    "hexo": "^6.0.0",
    "hexo-algoliasearch": "^1.0.0",
    "hexo-autoprefixer": "^2.0.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-feed": "^1.1.1",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-multi-next-markdown-it": "^0.1.7",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-theme-shokax": "^0.2.8",
    "yarn": "^1.22.19"
  }
}
```

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
第一个问题SXC改一下文件编码就能解决，下个版本统一改
第二个问题看起来是目录的问题，SXC用的npm源还是github源，github源需要自行编译
我这边由于环境问题没法开WSL，所以测试暂时没法进行

**Comment by you9you** [comment]
npm

**Comment by you9you** [comment]
> 第一个问题SXC改一下文件编码就能解决，下个版本统一改 第二个问题看起来是目录的问题，SXC用的npm源还是github源，github源需要自行编译 我这边由于环境问题没法开WSL，所以测试暂时没法进行

npm

**Comment by zkz098** [comment]
> npm

第二个问题目前看来是目录结构/文件名的问题，把_config.yml改成shokax后能正常运行吗
因为我这边测试发现在大小写严格的情况下使用"shokaX"和npm源会抛出WARN  No layout: index.html

**Comment by you9you** [comment]
> > npm
> 
> 第二个问题目前看来是目录结构/文件名的问题，把_config.yml的theme改成shokax后能正常运行吗 因为我这边测试发现在大小写严格的情况下使用"shokaX"和npm源会抛出WARN No layout: index.html

可以用，但也需要把`_config.shokaX.yml`改为`_config.shokax.yml`

**Comment by zkz098** [comment]
已于docs中添加注意事项
