### ISSUE TITLE
能否添加对于LaTex的支持，像诸如next之类的主题一样，增加对于数学公式，内联公式和多行公式的支持

### ISSUE THREAD

**Issue by cloudflaresni** [theme-shoka-x/hexo-theme-shokaX#107]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

主要是对于行内内联公式和行间多行公式的支持，目前是没有这方面的功能的，而且似乎最基本的数学公式符号渲染也不支持。没有办法渲染我的LaTex公式，基本上达不到Typora里面所见即所得的效果。网上的解决方案多数是十多年前的，而且对于小众主题，只能自己进行魔改。希望能够添加，感谢

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
front-matter里加上
```
math: true
```
就可以支持LaTex
e.g. https://d-sketon.top/20221229/clrs-book-note/

**Comment by zkz098** [comment]
已在docs中添加: https://docs.kaitaku.xyz/guide/tags.html#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F-katex

**Comment by cloudflaresni** [comment]
测试了之后发现似乎并不支持我的LaTex,目前的解决方案使用mathjax filter一个hexo插件替代渲染。使用的环境是typora1.5.10,shokax 0.2.4 。用mathtype导出的plain tex,在typora和mathjax插件的转换下都可以正常显示。但是按照开发者的解决方案还是无法渲染。

**Comment by zkz098** [comment]
> 测试了之后发现似乎并不支持我的LaTex,目前的解决方案使用mathjax filter一个hexo插件替代渲染。使用的环境是typora1.5.10,shokax 0.2.4 。用mathtype导出的plain tex,在typora和mathjax插件的转换下都可以正常显示。但是按照开发者的解决方案还是无法渲染。

能否提供LaTeX公式，理论上来说应该可以正常渲染

**Comment by cloudflaresni** [comment]
可以的，请问怎么发给您，发给您首页邮箱可以吗

**Comment by zkz098** [comment]
> 可以的，请问怎么发给您，发给您首页邮箱可以吗

发给`zkz20081204#126.com`这个
把#换成@

**Comment by cloudflaresni** [comment]
已经发送了，请查收

**Comment by zkz098** [comment]
这并不是KaTeX渲染的问题，而是由于这两者语法差异导致的
从mathjax迁移到KaTeX(尤其是ShokaX专属版)需要对语法做一些调整
我已将修改后的版本发回，请注意查收

**Comment by z0z0r4** [comment]
> 已在docs中添加: [docs.kaitaku.xyz/guide/tags.html#数学公式-katex](https://docs.kaitaku.xyz/guide/tags.html#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F-katex)

请问现在关于这个的文档在哪呢，未能搜到 `数学公式`
