### ISSUE TITLE
主页post list: more显示不正常?

### ISSUE THREAD

**Issue by duchenpaul** [theme-shoka-x/hexo-theme-shokaX#110]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

对比shoka (https://shoka.lostyu.me/)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/8120099/053da08c-f4b7-430c-a326-75e196922eff)

shokaX的more图标显示错位:
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/8120099/a7390d54-29f9-4657-8cdf-46a8d6b930ae)

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
21年10月之前的博客应该都是凸出来的
shoka最近的一次commit把这几行删了，个人感觉不算bug👀
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/d67c7832-0629-431d-ac32-0f90f4d6ee10)
