### ISSUE TITLE
增加latex svg渲染模式

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#113]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

也许对于含有大量公式的页面，使用svg能提升性能

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
KaTeX似乎不支持在渲染时输出SVG图像
如果更换为mathjax性能可能会更差

**Comment by zkz098** [comment]
等KaTeX支持SVG渲染再跟进()
