### ISSUE TITLE
chart 配置可选

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#114]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

frappe-charts 应该不是必须的组件吧，可以在配置文件里选择是否使用，防止引入不必要的js

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/7f5e112a-43b9-4eee-a188-3e1dfe274b6f)
shoka的vendor里就有这个，作用是和markdown-it-chart联动，理论上属于必须的组件
但是shoka的文档居然没有，导致这个功能几乎没人用()
