### ISSUE TITLE
一次部署的bug与建议

### ISSUE THREAD

**Issue by foryouos** [theme-shoka-x/hexo-theme-shokaX#119]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

其他问题

### 问题描述

# shokaX建议

> 尊敬的开发者你好，作为shoka的用户，越来越多的BUG，看到还有人继续维护并发展出来shokaX也觉得很欣慰，在这两天慢慢更换主题的时候，也遇到一些问题，和希望能够添加的功能想法，以下是我的想法与建议，希望开发者们能够好好考虑一下，也祝shokaX能够越来越好

## 视频播放

> 好像原有的视频播放功能不能使用啦！我在介绍里面也没有发现相关的视频内容的介绍

```markdown
{% media video %}

- name : "旅行记录"
  url : https://s138.ananas.chaoxing.com/video/fb/35/53/ead1480b90f8fb35d8f381d3aeb4944e/sd.mp4?at_=1679393695527
- name: "打铁花精彩版"  
  url: https://s138.ananas.chaoxing.com/video/54/47/ff/2b43035323b9e6b530edd8a1c96762f4/sd.mp4?at_=1679382875178
- name: "《演员》"  
  url: https://s138.ananas.chaoxing.com/video/c5/cf/65/7bf8c563a0ac7e368143a30b2839ed06/sd.mp4?at_=1679382171600
- name : 《丑八怪》
  url: https://s138.ananas.chaoxing.com/video/0b/f8/b3/44017eebeb7dc6c52ef10958e1ca89d2/sd.mp4?at_=1679382769501

{% endmedia %}
```
![image-20230613072029450](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/fdc71259-d93d-4610-a4f4-3735677c86b4)

## 评论夜景模式

> 评论区在在夜景模式下，不能兼容

![image-20230613071942291](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/3ae9a663-542b-4c1c-aa50-c7b6275ea32e)

## 代码设置适配问题

> shoka在IPad端的代码 旁边的数字编号 明显向下偏移，较为影响阅读体验
>
> 该false的都false了
>
> 我也专门开了一下您的网站，也存在这个问题在IPad端无论是微信还是Safari浏览器，Chrome都存在这个问题
>
> 

![fd0255c571d0aef55ac300adb30a039](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/a7277f35-6c3a-4ffe-ab08-299d3eee6667)

## 灯笼

> 灯笼要是仅置顶，不随着下移动，不遮挡搜索，能够看清完字，就好啦。慢慢来，奥利给

## 主题CSS自定义功能

> 我翻看了之前shoka的自定义主题设置,在source的_data里面自定义主题CSS，表示有点看不懂，_（可有可无，这是我的问题， 谢谢啦

![image-20230613084039220](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/ee1118bc-d6c3-4a72-940d-8c5270910de1)

## 404 页面

> 我在您的网站看到了，404页面在开发ing，此条可忽略
>
> 在shoka迁移到shokaX提到了，但是没有在使用指南提醒，我看迁移使用shokaX并没有404页面

* 需要在hexo根目录source目录下建立404.md
* 重新hexo clean
* hexo g
* hexo s之后并没有出现

![image-20230613093914994](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/6d85dea3-8f55-4057-8df3-d94df90b89ed)

* 只有当输入网址后面输入404之后才会出现，`我查看了您的网站，您的网站支持404页面`，不知道哪里步骤出现了问题

![image-20230613094624680](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/27468257-fa06-42f7-ba31-b969d2cda192)

## 后语

> 可以的话，我也提交一下开发文档，原谅只懂`HTML 和CSS 和基本JS` 方向在C++后台服务器。作者加油

## 优化 `SEO`

> 在您的网站上看到的

### 安装``hexo-filter-nofollow`

```##
cnpm i hexo-filter-nofollow
```

### 配置`根`目录`config.yml`

```cpp
nofollow:
  enable: true # 是否启用
  field: site #site 全站，post 仅文章
  exclude:
    - 'www.kaitaku.xyz' #例外网站
```

### 相关配置

使用最新的0.29
hexo6.9 和nodejs  20.都是最新版的

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
文档在 https://github.com/theme-shoka-x/shokaX-docs 仓库，基于VuePress V2实现，欢迎提交开发文档
如果需要加新栏目(新页面)可以在 PR 里说一声，我会添加相关的配置文件

**Comment by foryouos** [comment]
好的，谢谢啦
开发文档 我今天提交了两个SEO和主题标题修改图片更换等，我在原有基础上改的
