### ISSUE TITLE
图片呈现&返回&手机端标题&电脑端bug

### ISSUE THREAD

**Issue by foryouos** [theme-shoka-x/hexo-theme-shokaX#121]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

无法判断

### 问题描述

* 标题问题
- 标题呈现问题 : 在手机端标题最后是个  `-`  ，好奇怪，所有的文章都是，在手机端平板端都存在此问题，我看了您的网站也存在此问题
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/0c579088-efe1-4236-9fe6-3c66c1f36863)

* 图片呈现
- 图片如果在电脑端浏览器直接点击后退，页面后退，但是图片还保存呈现
- 手机端后退和电脑端一样的问题，
- 希望能够降低查看图片时周围黑色的透明度
- 电脑端鼠标点击非图片区域，照片可以恢复到文章中，手机端却不可以，要点右上角的 x 才可以，比较影响体验

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/0e6afde9-61d9-4651-8ec1-154e6115b78b)

### 复现步骤

对比了浏览器，清除了缓冲，对了了其它网站

### 相关配置

皆使用最新版本

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
标题显示已确定为BUG，0.2.10将会修复
图片的显示问题是因为pjax的后退并非实际后退，所以图片不会自己消失，会考虑人工添加一个监听器处理这个问题
我这边测试手机端点击非图片区域也可以恢复到文章界面

**Comment by foryouos** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/3e8ec87f-e94b-46ea-9bee-db2b97174dc9)
点击非图片区域，在手机端&Chrome浏览器&火狐浏览器 测试确实不能恢复到文章界面 @zkz098 
电脑端的话，启动手机模式，载刷新一下，确实不可以的，希望能够再测试一下。麻烦您啦

**Comment by D-Sketon** [comment]
我这里手机端需要双击才可以退出

**Comment by zkz098** [comment]
从手机端测试了一下，单击确实没法退出，但双击可以
这个也许是故意为之，防止缩放图片时意外退出

**Comment by foryouos** [comment]
那应该是我设置的问题，IQOO手机端浏览器&Chrome&微信  双击非图片区域就直接方法图片啦
