### ISSUE TITLE
歌词显示

### ISSUE THREAD

**Issue by foryouos** [theme-shoka-x/hexo-theme-shokaX#127]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/58133210/bd0c5665-9394-4659-a7e3-ab320ca4430b)

### 复现步骤

歌词问题

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
#126 已修复

**Comment by zkz098** [comment]
0.2不会发布新的版本，这个会在0.3版本修复，预计未来一个月内可以顺利发布

**Comment by zkz098** [comment]
0.3预览版已发
