### ISSUE TITLE
md渲染数学公式出现重复

### ISSUE THREAD

**Issue by tiaotiaohu98** [theme-shoka-x/hexo-theme-shokaX#128]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

md渲染数学公式出现重复
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/51284460/67a7b89e-1760-4c46-b2e1-2e3191111bf8)

### 复现步骤

no

### 相关配置

node18 

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
根据已知信息，可能是mathjax和katex冲突导致的，请确保没有安装其他数学渲染插件(例如mathjax)
如果卸载/确认不存在之后仍存在，请回复此条

**Comment by cloudflaresni** [comment]
> 根据已知信息，可能是mathjax和katex冲突导致的，请确保没有安装其他数学渲染插件(例如mathjax) 如果卸载/确认不存在之后仍存在，请回复此条 参见: https://www.zhihu.com/question/267011398

想借楼提问一下，能否卸载原有的katex,用hexo-filter-mathjax和pandoc替代呢，自己测试总是有冲突的地方，但是却没啥具体的报错，就是hexo g失败，可否请开发者测试一下，感谢

**Comment by zkz098** [comment]
> 想借楼提问一下，能否卸载原有的katex,用hexo-filter-mathjax和pandoc替代呢，自己测试总是有冲突的地方，但是却没啥具体的报错，就是hexo g失败，可否请开发者测试一下，感谢

KaTeX由服务端渲染，内置于md渲染器中，需要自行修改渲染器

**Comment by zkz098** [comment]
> 想请教一下，这个mathjax和katex只能留一个，非此即彼，不能共存，对吧

对。两个共存轻则渲染重复重则跑不起来
