### ISSUE TITLE
当开启 waline 评论的时候再打开 auto_scroll: true 会将评论的输入框吃掉

### ISSUE THREAD

**Issue by test19124** [theme-shoka-x/hexo-theme-shokaX#130]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

版本 `Theme.ShokaX v0.2.10` 

当开启 waline 评论的时候再打开 auto_scroll: true 会将评论的输入框吃掉。
关闭 auto_scroll 才能显示评论的输入框。

### 复现步骤

开启 waline 评论的时候同时打开 auto_scroll: true 

### 相关配置

Theme.ShokaX v0.2.10
nodejs v18.16.1 
npm v9.8.0 
hexo-cli v4.3.1

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
本地无法复现
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/d700284b-ef97-42f1-9af5-4ef8ef7a007e)
