### ISSUE TITLE
最新評論的網站標題無法自定義

### ISSUE THREAD

**Issue by Jim137** [theme-shoka-x/hexo-theme-shokaX#132]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

如下，
https://github.com/theme-shoka-x/hexo-theme-shokaX/blob/6733e7e3054ee07129818a016fdd19b2b7084703/layout/_mixin/widgets.pug#L24
該代碼沒有配置自定義選項。

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
已在 https://github.com/theme-shoka-x/hexo-theme-shokaX/commit/9cf92e08264297a92f38e0a309bc5258e4502bc4 中补充缺失本地化键
