### ISSUE TITLE
关于waline评论加载不出来的问题

### ISSUE THREAD

**Issue by af744dcgerz** [theme-shoka-x/hexo-theme-shokaX#135]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

启用了waline评论系统，但是文章底部一直都没有加载出来评论区。
我用控制台看了一下，发现可能是这个的原因。
![屏幕截图 2023-07-29 101720](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/114892186/285eee67-05de-421c-bb64-8ab0a3a0ddb6)
并且最终指向了这里，
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/114892186/6b83d5c2-e274-4709-bf8a-f591a7c5f335)
是不是因为这个原因才导致waline没加载出来

### 复现步骤

```
hexo clean
hexo g
hexo s
```

### 相关配置

shokaX v0.3.0
nodejs v18.17.0
npm v9.8.1

### 注意事项

- [x] 我已确认以上事项

**Comment by zkz098** [comment]
社区已有人修复，正在等PR
如果8月1日还没有PR我就修了（

**Comment by zkz098** [comment]
已修，等下一个版本发布
