### ISSUE TITLE
按照文档中的方法更改背景轮播图片无效，只能通过更改hexo-theme-shokax包中的_images.yml实现背景轮播图片的替换

### ISSUE THREAD

**Issue by fyhtrainee** [theme-shoka-x/hexo-theme-shokaX#142]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

无法判断

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92796095/ca19d1f8-ba48-47b7-ab6e-bb67fca0f41f)
在该文件下的设置无法生效，但是
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92796095/f2c84bfc-004d-4002-9183-313dd1f10ae8)
直接更改该图中的_images.yml可以生效

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
文档有点问题，这种方式更改需要把`_images.yml`改成`images.yml`
稍后我修改一下文档

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/e7a11825-968d-4ed7-8914-ac1967e1c3a3)
文档里就是`images.yml`啊（

**Comment by fyhtrainee** [comment]
没错，可是我按照这个方法更改不了轮播图片
![Uploading image.png…]()

**Comment by zkz098** [comment]
图片上传失败，重新传一张

**Comment by fyhtrainee** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92796095/903abd69-a5c9-4513-a081-db2f8b50e456)
没错，我说的就是image.yml配置无法生效

**Comment by zkz098** [comment]
没问题，但是没法复现
运行`hexo cl`了吗

**Comment by fyhtrainee** [comment]
运行了，日志这边也看不到啥问题，只能改_images.yml才会生效

**Comment by fyhtrainee** [comment]
还有一个问题就是在将md文件中，audio的url对palyerAPI中配置的网站也就是 https://api.injahow.cn 发送请求的时候会出现跨域问题，这个是否存在对应的配置。
`Access to fetch at 'https://api.injahow.cn/meting/api?server=netease&type=song&id=1387098940&r=0.9477065327767975' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by zkz098** [comment]
> 运行了，日志这边也看不到啥问题，只能改_images.yml才会生效

怪问题，我这边没法复现，看看有没有其他人能复现
这个改_data的方法本身原理就未知，如果没法复现就很难解决

**Comment by zkz098** [comment]
> 还有一个问题就是在将md文件中，audio的url对palyerAPI中配置的网站也就是 https://api.injahow.cn 发送请求的时候会出现跨域问题，这个是否存在对应的配置。 `Access to fetch at 'https://api.injahow.cn/meting/api?server=netease&type=song&id=1387098940&r=0.9477065327767975' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

这个只能找API方面的人处理，fetch应该是没有匿名模式的（但老式API有）

**Comment by fyhtrainee** [comment]
> > 运行了，日志这边也看不到啥问题，只能改_images.yml才会生效
> 
> 怪问题，我这边没法复现，看看有没有其他人能复现 这个改_data的方法本身原理就未知，如果没法复现就很难解决

没事，那我先改_images.yml可以暂时解决，但是跨域的那个问题我现在还解决不了，不知道在哪儿配置

**Comment by fyhtrainee** [comment]
> > 还有一个问题就是在将md文件中，audio的url对palyerAPI中配置的网站也就是 https://api.injahow.cn 发送请求的时候会出现跨域问题，这个是否存在对应的配置。 `Access to fetch at 'https://api.injahow.cn/meting/api?server=netease&type=song&id=1387098940&r=0.9477065327767975' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> 这个只能找API方面的人处理，fetch应该是没有匿名模式的（但老式API有）

我感觉可能是网站api改了路径，导致的404问题，刚刚又看了一下
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92796095/1f999924-886f-4d8c-926d-cc9a5b5f0702)

**Comment by zkz098** [comment]
> 

确实是，马上修

**Comment by fyhtrainee** [comment]
# hexo init
npm install shokax-cli --location=global
# cd your_blog
SXC install shokaX
我是按照这个命令走下来的，刚刚看了一下版本好像是0.1.1版本的，可以问一下怎么获取最新版本的theme吗
{
  "name": "hexo-theme-shokax",
  "version": "0.1.1",
  "description": "a hexo theme based on shoka",
  "main": "index.js",
  "repository": "https://github.com/zkz098/hexo-theme-shokaX",
  "author": "Chou kaitaku",
  "license": "BSD-3-Clause",
  "scripts": {
    "test": "cd ./source/js && tsc"
  },

**Comment by fyhtrainee** [comment]
# hexo init
npm install shokax-cli --location=global
# cd your_blog
SXC install shokaX

**Comment by fyhtrainee** [comment]
我这边再重新解决一下，应该是我的问题

**Comment by fyhtrainee** [comment]
`app.js?v=0.3.4:1 Uncaught (in promise) TypeError: this.options.rawList.forEach is not a function
    at app.js?v=0.3.4:1:29145
    at new Promise (<anonymous>)
    at Object.fetch (app.js?v=0.3.4:1:29040)
    at Object.load (app.js?v=0.3.4:1:28942)
    at ha (app.js?v=0.3.4:9:7567)
    at Ba (app.js?v=0.3.4:9:24031)`
但是更换到最新版本之后，会出现之前的问题。这个问题再0.1.1版本中没有出现

**Comment by fyhtrainee** [comment]
`audio:
  - title: 列表1
    list:
      - https://music.163.com/#/playlist?id=2943811283
      - https://music.163.com/#/playlist?id=2297706586
  - title: 列表2
    list:
      - https://music.163.com/#/playlist?id=2031842656
  `
这个是_config.shokax.yml中的配置，再主页中，这个播放是可行的，但是在文章中，这个按钮却不起反应，并会回复刚刚的错误。这个是我.md文件中的配置
`
---
title: Hello World
audio:
  - https://music.163.com/#/playlist?id=2943811283
  - https://music.163.com/#/playlist?id=2297706586
  - https://music.163.com/#/playlist?id=2031842656
---
`

**Comment by zkz098** [comment]
> 我是按照这个命令走下来的，刚刚看了一下版本好像是0.1.1版本的，可以问一下怎么获取最新版本的theme吗 `{ "name": "hexo-theme-shokax", "version": "0.1.1", "description": "a hexo theme based on shoka", "main": "index.js", "repository": "https://github.com/zkz098/hexo-theme-shokaX", "author": "Chou kaitaku", "license": "BSD-3-Clause", "scripts": { "test": "cd ./source/js && tsc" },·`

有好多人都是0.1.1版本的，而且是全新安装，目前正在调查原因。可能和gitee有关(gitee仓库就是0.1.1的)
如果是某教程推荐使用gitee源或者人工clone了gitee源，直接发给我，我去和作者联系一下

**Comment by zkz098** [comment]
> ```
> audio:
>   - title: 列表1
>     list:
>       - https://music.163.com/#/playlist?id=2943811283
>       - https://music.163.com/#/playlist?id=2297706586
>   - title: 列表2
>     list:
>       - https://music.163.com/#/playlist?id=2031842656
> ```
> 
> 这个是_config.shokax.yml中的配置，再主页中，这个播放是可行的，但是在文章中，这个按钮却不起反应，并会回复刚刚的错误。这个是我.md文件中的配置
> 
> ```
> ---
> title: Hello World
> audio:
>   - https://music.163.com/#/playlist?id=2943811283
>   - https://music.163.com/#/playlist?id=2297706586
>   - https://music.163.com/#/playlist?id=2031842656
> ---
> ```

正在排查，可能和audio获取有关系

**Comment by zkz098** [comment]
images问题换成0.3.4之后修好了吗 @fyhtrainee

**Comment by zkz098** [comment]
0.3.5已修复audio问题，其他问题等待进一步回复

**Comment by fyhtrainee** [comment]
> images问题换成0.3.4之后修好了吗 @fyhtrainee

抱歉，刚刚下班到家，images.yml的问题依旧存在，并且我的一位同事也遇到了这个问题，我相信这个问题是可以复现的。

至于为什么是0.1.1版本，我目前还没有头绪，有可能和`SXC install shokaX`执行的位置有关，就是执行的目录，当然这只是我的猜测。

**Comment by zkz098** [comment]
> > images问题换成0.3.4之后修好了吗 @fyhtrainee
> 
> 抱歉，刚刚下班到家，images.yml的问题依旧存在，并且我的一位同事也遇到了这个问题，我相信这个问题是可以复现的。
> 
> 至于为什么是0.1.1版本，我目前还没有头绪，有可能和`SXC install shokaX`执行的位置有关，就是执行的目录，当然这只是我的猜测。

这有啥抱歉的（
images这个问题很玄学，根据目前来看，很可能文档里的配置能正常运行才是偶发性的，因为加载_images的代码并没有从_data加载的逻辑，这个至今还是TODO。但部分环境下又可以从_data加载，很难理解，也许是hexo内部机制

0.1.1这个版本号唯一特殊的就是gitee仓库是这个版本，估计就是SXC可能走错仓库了，新版本测试可以正常安装0.3.5了

**Comment by fyhtrainee** [comment]
我觉得你可以检查一下你对滚动背景图片的数量限制（尤其是针对用户自定义的images.yml文件，当然，如果你有分开处理的话），我刚刚测试了当图片数量小于7张之后无法正常读取图片，会读取默认图片，当大于七张后会读取source下_data文件夹下images.yml中的图片信息

**Comment by zkz098** [comment]
> 我觉得你可以检查一下你对滚动背景图片的数量限制（尤其是针对用户自定义的images.yml文件，当然，如果你有分开处理的话），我刚刚测试了当图片数量小于7张之后无法正常读取图片，会读取默认图片，当大于七张后会读取source下_data文件夹下images.yml中的图片信息

这个是设计之一，因为如果图片数量小于6的话_cover函数会运行错误，且随机性会失效
目前看来这个加载方法应该是依赖于hexo内置的机制，我稍后会在文档添加相关说明

**Comment by fyhtrainee** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92796095/a040269e-f143-4cab-a04a-b6c3232e8f85)
还有就是这个样式重叠的问题，是我的配置没有配对吗，可是我是按照文档中md的配置直接复制粘贴过来的。还是说是hexo的问题，或者其他插件的问题。

**Comment by zkz098** [comment]
> ![image](https://user-images.githubusercontent.com/92796095/263271322-a040269e-f143-4cab-a04a-b6c3232e8f85.png) 还有就是这个样式重叠的问题，是我的配置没有配对吗，可是我是按照文档中md的配置直接复制粘贴过来的。还是说是hexo的问题，或者其他插件的问题。

你hexo的prsimjs下的enable没关。
你启动的时候ShokaX应该提示了`[SXEC 101]`，这个就是代码块渲染错误的警告

**Comment by fyhtrainee** [comment]
问题解决了，谢谢你

> > ![image](https://user-images.githubusercontent.com/92796095/263271322-a040269e-f143-4cab-a04a-b6c3232e8f85.png) 还有就是这个样式重叠的问题，是我的配置没有配对吗，可是我是按照文档中md的配置直接复制粘贴过来的。还是说是hexo的问题，或者其他插件的问题。
> 
> 你hexo的prsimjs或者highlight下的enable没关。 你启动的时候ShokaX应该提示了`[SXEC 101]`，这个就是代码块渲染错误的警告

**Comment by zkz098** [comment]
好的，这个 Issue 先Close了，后续有问题再新开Issue
