### ISSUE TITLE
SXC 安装过程中网络和命令意义不明的问题

### ISSUE THREAD

**Issue by yuan-uyume** [theme-shoka-x/hexo-theme-shokaX#144]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

其他问题

### 问题描述

1. SXC install -r=github shokaX 该命令意义不明。情况一： 在 ./themes/shokaX 文件夹不存在或者为空时，无法自行克隆并安装依赖。 情况二： 在 ./themes/shokaX文件夹为克隆项目文件夹时，使用命令后会在./下创建shokaX文件夹，但报错“Error: hexo-renderer-multi-next-markdown-it not installed”
2. SXC install shokaX 时非常容易因为国内网络问题导致安装失败，同时其中浏览器内核一直下载安装失败，使用全局魔法依旧不能改善下载问题。下载的主题放在了模块文件夹下，未说明的情况下很难发现。

建议：1. 提升sxc的傻瓜化程度，依赖使用镜像
2. 让我能用魔法也行啊

### 相关配置

在多台电脑上，多种环境上都会发生。

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
因为-r=github已经在0.0.6被干掉了（
github模式需要走action并解压zip，代码暂时未实现，现版本只支持npm源

我之前测试的时候puppeteer的链接是能直通的，然后之前的puppeteer-cn长时间不维护不兼容新版npmmirror所以就移除了，现在可能网络状态又复杂了。把`TUN`模式打开试试。
主题放在模块目录下这个不是挺正常的吗（。hexo从5.0开始支持npm源主题，非个人的主题也大多都建议从npm安装，可能因为ShokaX是为数不多的强制npm源主题

**Comment by yuan-uyume** [comment]
> 因为-r=github已经在0.0.6被干掉了（ github模式需要走action并解压zip，代码暂时未实现，现版本只支持npm源
> 
> 我之前测试的时候puppeteer的链接是能直通的，然后之前的puppeteer-cn长时间不维护不兼容新版npmmirror所以就移除了，现在可能网络状态又复杂了。把`TUN`模式打开试试。 主题放在模块目录下这个不是挺正常的吗（。hexo从5.0开始支持npm源主题，非个人的主题也大多都建议从npm安装，可能因为ShokaX是为数不多的强制npm源主题

非常感谢作者的回复，有这样活跃的作者，我很看好shokax主题的发展。
为了主题更受欢迎也为了更多的人能方便的用上shokax主题，希望作者能及时的更新shokax的配置安装文档，并尽可能的简单易懂。因为从昨天开始，到现在我都还没能安装使用上贵主题。

**Comment by zkz098** [comment]
> 

这个问题需要重写上游供应链，短时间解决不了，先走手动安装
```bash
npm i hexo-theme-shokax
npm i hexo-renderer-multi-next-markdown-it --ignore-scripts
npm i hexo-autoprefixer
npm i hexo-algoliasearch
npm i hexo-feed
```
把npm换成你用的包管理器，如果仍然失败:
```bash
npm i cnpm -g
npm i hexo-theme-shokax
cnpm i hexo-renderer-multi-next-markdown-it --ignore-scripts
npm i hexo-autoprefixer
npm i hexo-algoliasearch
npm i hexo-feed
```

**Comment by yuan-uyume** [comment]
> > 
> 
> 这个问题需要重写上游供应链，短时间解决不了，先走手动安装
> 
> ```shell
> npm i hexo-theme-shokax
> npm i hexo-renderer-multi-next-markdown-it --ignore-scripts
> npm i hexo-autoprefixer
> npm i hexo-algoliasearch
> npm i hexo-feed
> npm i theme-shokax-pjax
> npm i theme-shokax-anime
> npm i lozad
> npm i esbuild
> ```
> 
> 把npm换成你用的包管理器，如果仍然失败:
> 
> ```shell
> npm i cnpm -g
> npm i hexo-theme-shokax
> cnpm i hexo-renderer-multi-next-markdown-it --ignore-scripts
> npm i hexo-autoprefixer
> npm i hexo-algoliasearch
> npm i hexo-feed
> npm i theme-shokax-pjax
> npm i theme-shokax-anime
> npm i lozad
> npm i esbuild
> ```
感谢，目前已经通过npm i esbuild hexo-theme-shokax hexo-algoliasearch hexo-autoprefixer hexo-feed hexo-generator-archive hexo-generator-category hexo-generator-index hexo-generator-tag hexo-renderer-multi-next-markdown-it hexo-renderer-pug hexo-renderer-stylus lozad theme-shokax-anime theme-shokax-pjax 安装成功。

**Comment by yuan-uyume** [comment]
不知道后续开发有没有考虑两个功能：1. 对不同标签的文章，在文章开始置顶一个内容。场景：在图床为github的文章里，在最开头提醒图源为github需要魔法正常访问。2. 能够更换加载动画。
然后是一个问题：开启长文章优化会导致文章多级标题的H1、H2、H3不显示，这是特性还是bug.

**Comment by zkz098** [comment]
> 不知道后续开发有没有考虑两个功能：1. 对不同标签的文章，在文章开始置顶一个内容。场景：在图床为github的文章里，在最开头提醒图源为github需要魔法正常访问。2. 能够更换加载动画。 然后是一个问题：开启长文章优化会导致文章多级标题的H1、H2、H3不显示，这是特性还是bug.

第一个有计划，第二个已支持，但是支持不完善，后期会考虑支持Inject
长文章优化的一切问题都是特性，因为这个是最终解决方案，出现任何问题都是正常且难以修复的
