### ISSUE TITLE
hexo g的时候出现错误

### ISSUE THREAD

**Issue by Hartcher1996** [theme-shoka-x/hexo-theme-shokaX#147]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

ERROR Failed to detect version info. Error message:
ERROR
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:967:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12)

### 相关配置

hexo: 6.3.0
hexo-cli: 4.3.1
os: win32 10.0.22621
node: 18.17.1
acorn: 8.8.2
ada: 2.5.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.0
icu: 73.1
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.12
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
网络问题，可以忽略
