### ISSUE TITLE
文章列表图片可以更换吗

### ISSUE THREAD

**Issue by Hartcher1996** [theme-shoka-x/hexo-theme-shokaX#148]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

其他问题

### 问题描述

`<img data-src="https://i.imgtg.com/2023/03/09/YSj7p.jpg" alt="article cover" src="https://i.imgtg.com/2023/03/09/YSj7p.jpg" data-loaded="true" class="lozaded">`
前端显示是这样的，然后我按照_images.yml说明添加了图片 
`- 图片链接`
hexo g之后还是显示的这个图片

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
https://docs.kaitaku.xyz/guide/theme.html#%E7%BD%91%E7%AB%99%E8%BD%AE%E6%92%AD%E5%9B%BE%E8%87%AA%E5%AE%9A%E4%B9%89
图片数量少于6时不会触发更换

**Comment by zkz098** [comment]
如果多次都是同一个图片不排除运气太好
