### ISSUE TITLE
支持本地搜索

### ISSUE THREAD

**Issue by Hartcher1996** [theme-shoka-x/hexo-theme-shokaX#149]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

https://linn-ylz.com/Hexo/blog-search-config/
这篇文章，写了给Shoka改成本地搜索
想问下怎么把ShokaX也改成本地搜索

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
不会提供官方支持，`algolia`的使用额度个人是够用的。
日后可能会提供plugin支持，但优先级很低

**Comment by zkz098** [comment]
Astro / Valaxy 版本实现后考虑向后迁移，长期推迟
