### ISSUE TITLE
目前最新版0.3.5不支持 Rocket Loader™，更新之后会复现之前大概0.2.5的问题，开启之后无限转圈

### ISSUE THREAD

**Issue by MisakaMikoto521** [theme-shoka-x/hexo-theme-shokaX#150]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

目前最新版0.3.5不支持 Rocket Loader™，更新之后会复现之前大概0.2.5的问题，开启之后无限转圈

### 复现步骤

目前最新版0.3.5不支持 Rocket Loader™，更新之后会复现之前大概0.2.5的问题，开启之后无限转圈

### 相关配置

都是最新的版本

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
```typescript
const siteInit = () => {
  cloudflareInit()
  // ...
  }
  
  window.addEventListener('DOMContentLoaded', siteInit, {
  passive: true
})
```
补发DOMContentLoaded的函数需要DOMContentLoaded触发（

**Comment by D-Sketon** [comment]
> ```typescript
> const siteInit = () => {
>   cloudflareInit()
>   // ...
> }
>   
> window.addEventListener('DOMContentLoaded', siteInit, {
> passive: true
> })
> ```
> 补发DOMContentLoaded的函数需要DOMContentLoaded触发（

这块不是很懂，不怎么会修（）

**Comment by zkz098** [comment]
> > ```ts
> > const siteInit = () => {
> >   cloudflareInit()
> >   // ...
> > }
> >   
> > window.addEventListener('DOMContentLoaded', siteInit, {
> > passive: true
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 补发DOMContentLoaded的函数需要DOMContentLoaded触发（
> 
> 没用过rocket loader，这块不是很懂，不怎么会修（）

因为rocket-loader会把DOMContentLoaded吞掉，需要手动重发事件
我觉得0.3.6修好了（
