### ISSUE TITLE
无法从Github拉取主题，貌似文件不存在

### ISSUE THREAD

**Issue by nixingshiguang** [theme-shoka-x/hexo-theme-shokaX#153]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

其他问题

### 问题描述

$ SXC install -r=github shokaX
INFO  Looking for packageManager...
INFO  Using package manager: yarn
fatal: repository './themes/shokaX' does not exist
ERROR Install theme failed: git clone error
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/94590099/1fa35e95-2c95-4bbb-baf3-cc6b37c6c9c9)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
github源已弃用，无法适配0.3+文件结构，且现版本从git clone的代码无法正常使用，请使用actions的预编译版本
