### ISSUE TITLE
鼠标单击烟花特效问题

### ISSUE THREAD

**Issue by Raqtpie** [theme-shoka-x/hexo-theme-shokaX#154]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

在script.js中，第49行代码如下：
fireworks: undefined
似乎这行到底烟花特效不能正确配置，配置为theme.fireworks后，单击页面烟花颜色全部为黑色，颜色不正确
不修改行在_config.yml配置如下没有烟花特效：
fireworks:
  enable: false # 是否启用
  color: # 烟花颜色
    - "rgba(255,182,185,.9)"
    - "rgba(250,227,217,.9)"
    - "rgba(187,222,214,.9)"
    - "rgba(138,198,209,.9)"

### 复现步骤

试图修改/script/generaters/scirpt.js中的第49行触发烟花特效

在_config.yml中设置
fireworks:
  enable: false # 是否启用
  color: # 烟花颜色
    - "rgba(255,182,185,.9)"
    - "rgba(250,227,217,.9)"
    - "rgba(187,222,214,.9)"
    - "rgba(138,198,209,.9)"

### 相关配置

shokaX版本为最新版，SXC安装
检查过theme-shokax-anime依赖
edge、firefox均测试过

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
theme.fireworks => theme.fireworks.color
之后我会提交PR修复
