### ISSUE TITLE
建议提供便捷的升级方式

### ISSUE THREAD

**Issue by MisakaMikoto521** [theme-shoka-x/hexo-theme-shokaX#157]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

因为主题更新频繁，所以希望能有便捷的升级方式，不想每次都从头重新安装主题进行配置。
因为会更改一些备案的信息，在主页页脚，会更改layout,希望更新主题的时候能够保留

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
https://www.kaitaku.xyz/webbuild/shokaXplugin/ 中的`status`能否满足需求
