### ISSUE TITLE
建议shokax-cli使用的时候不需要root权限

### ISSUE THREAD

**Issue by MisakaMikoto521** [theme-shoka-x/hexo-theme-shokaX#158]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

在linux系统上，用SGX安装主题的时候，会请求root权限，不够安全，希望有更安全不需要root的方式

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
SXC没有主动请求过root权限，可能是包管理器或者其他指令被动请求的
