### ISSUE TITLE
长文章优化导致md渲染不正确

### ISSUE THREAD

**Issue by Raqtpie** [theme-shoka-x/hexo-theme-shokaX#159]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

开启实验性特性长文章优化时，md文档中的分点如 * - 1. 这种不能够在网页上正常显示
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/109587205/ebb7d65b-b893-4b69-a428-ecc943f4020e)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/109587205/1b5ad8e0-a1ea-4e5b-b9b3-b286b0643e32)
类似如上图片

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
可以稳定复现，确认为LPO导致的CSS失效

**Comment by D-Sketon** [comment]
content-visibility限制了li的宽度，导致采用绝对定位的伪类无法显示

**Comment by D-Sketon** [comment]
可能无法修复

**Comment by zkz098** [comment]
暂时关闭，等待更好的方案
