### ISSUE TITLE
hexo-feed 未适配 hexo-v7

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#168]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

由于hexo-feed 1.1.1还未适配 hexo v7，所以在安装其他依赖时可能会出现
```text
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: hexo-feed@1.1.1
npm ERR! Found: hexo@7.0.0
npm ERR! node_modules/hexo
npm ERR!   hexo@"^7.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer hexo@"^4.2.0 || ^5.2.0 || ^6.1.0" from hexo-feed@1.1.1
npm ERR! node_modules/hexo-feed
npm ERR!   hexo-feed@"^1.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: hexo@6.3.0
npm ERR! node_modules/hexo
npm ERR!   peer hexo@"^4.2.0 || ^5.2.0 || ^6.1.0" from hexo-feed@1.1.1
npm ERR!   node_modules/hexo-feed
npm ERR!     hexo-feed@"^1.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
待https://github.com/sergeyzwezdin/hexo-feed/pull/7 被merge并发布1.1.2后该PR可自行关闭

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
[hexo-feed/#7](https://github.com/sergeyzwezdin/hexo-feed/pull/7)已Merged，可close

**Comment by FidStyle** [comment]
@zkz098 
> 感觉可能短时间内适配不了了（）

一语成谶（）

**Comment by zkz098** [comment]
> @zkz098
> 
> > 感觉可能短时间内适配不了了（）
> 
> 一语成谶（）

好好好（

另外注意看一下邮箱，有ShokaX开发组的 invitation，通过即可加入

**Comment by FidStyle** [comment]
> > @zkz098
> > > 感觉可能短时间内适配不了了（）
> > 
> > 
> > 一语成谶（）
> 
> 好好好（
> 
> 另外注意看一下邮箱，有ShokaX开发组的 invitation，通过即可加入

nice，已join ＾∀＾
