### ISSUE TITLE
建议支持背景图封面图调用各自图床

### ISSUE THREAD

**Issue by AquaOH** [theme-shoka-x/hexo-theme-shokaX#170]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

_images.yml设置的图床会被背景和封面共同调取
能否让背景调用A图床,封面调用B图床?
我设想是:
A图床放高分辨率图
B图床放低分辨率图
这样能节省流量

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
0.3.7已添加
