### ISSUE TITLE
Categories页面 无法显示文章所在的最近一级文类

### ISSUE THREAD

**Issue by AquaOH** [theme-shoka-x/hexo-theme-shokaX#171]
### Before raising the issue...

- [X] I understand that Issues are used for providing feedback and resolving problems, and I will provide as much information as possible to help solve the issue.
- [X] I have filled in a short and clear title to help developers quickly identify the general problem when they receive the issue, instead of using vague titles like "an issue" or "error occurred".
- [X] I have confirmed that the latest version has not fixed this problem and no one has previously reported this issue.

### Issue occurrence location

Hexo rendering is incorrect (undefined text or blank, etc.)

### Issue description

**ShokaX:**
<img width="437" alt="26eb7b58f8cfaa41627fbf071ffa3555" src="https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/108086130/680e94ba-65d3-47da-a021-cf33a8a920a6">

**Shoka:**
<img width="264" alt="7b26a3b583ab1f0325f010b218c8174e" src="https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/108086130/3a688a23-8730-400e-8e7b-5f4159bdd25f">

个人尝试仿照Shoka的效果修改了一下:
hexo-theme-shokax/layout/category.pug

修改前:

```
        each post in posts.toArray()
            if post.categories && post.categories.length
                - var cat_length = post.categories.length
                each cat,index in post.categories.toArray()
                    if cat.name == page.title
                        - var lastcat = ""
                        - var lastcatslug = ""
                    else
                        - var lastcat = true
                        mixin lastcat
                            != lastcat
                            a(href=url_for(cat.path))
                                != cat.name
                            small
                                if index >= post.categories.toArray().length
                                    != cat.length
                                else
                                    #{'/'}
                    - var lastcatslug = lastcatslug + cat.slug
            if lastcat && lastcatslug && lastcatslug !== current
                h3(class="item section")
                    +lastcat
                - var current = lastcatslug
```

修改后:

```
        each post in posts.toArray()
            if post.categories && post.categories.length
                - var cat_length = post.categories.length
                each cat,index in post.categories.toArray()
                    if cat.name == page.title
                        - lastcat = ""
                        - lastcatslug = ""
                    else
                        - lastcat += `<a href=${url_for(cat.path)}>${cat.name}</a><small>`
                            if index >= post.categories.toArray().length-1
                                - lastcat = lastcat+' ( '+cat.length+' ) '+`</small>`
                            else
                                - lastcat = lastcat+'/'+`</small>`
                    - lastcatslug = lastcatslug + cat.slug
            if lastcat && lastcatslug && lastcatslug !== current
                h3(class="item section")
                    !=lastcat
                - current = lastcatslug
```

结果:

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/108086130/6526f0a9-d6fc-4b0a-b19f-e945ffaa7dc6)

### Reproduction steps

1. Hexo根目录 `_config.yml`设置三个category_map键值
```
category_map:
  计算机科学: computer-science
  体系结构: systemed-structures
  深入理解计算机系统: csapp
```
2. 在`source/post/computer-science/systemed-structures/csapp`内放置`test.md``test1.md`,`Front-matter`均为`[计算机科学, 体系结构, 深入理解计算机系统]`
3. `source/post/computer-science`放置`cover.jpg`，在主页显示分类卡片
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/108086130/465fbc49-88e7-411d-ae8b-ccadab15932b)

4. 点击卡片翻转后more进入页面
5. 显示界面如下，缺少`深入理解计算机系统`这个最近一级分类
<img width="437" alt="26eb7b58f8cfaa41627fbf071ffa3555" src="https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/108086130/e9b8ee25-889b-4c71-9b0d-be832bb5ec5b">

### Relevant configurations

Hexo 6.3.0
ShokaX 0.3.6
Nodejs 20.9.0
Edge 119.0.0.0

### Native Language

Chinese

### Important notes

- [X] I have confirmed the above notes.

**Comment by zkz098** [comment]
其实您可以直接发PR的（）
