### ISSUE TITLE
轮播图加载错误

### ISSUE THREAD

**Issue by skadiscarlet** [theme-shoka-x/hexo-theme-shokaX#179]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [ ] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

默认不会加载用户定义在source/_data/image_index.yml的配置，并且doc中写的是_image_index.yml也有问题

### 复现步骤

scripts/config.js中：
```
    if (data.images && data.images.length > 0) {
        hexo.theme.config.image_list = data.images;
    }
    else {
        hexo.theme.config.image_list = js_yaml_1.default.load(node_fs_1.default.readFileSync(path_1.default.join(__dirname, '../../_images.yml'), { encoding: 'utf-8' }));
    }
    if (node_fs_1.default.existsSync(path_1.default.join(__dirname, '../../_images_index.yml'))) {
        hexo.theme.config.index_images = js_yaml_1.default.load(node_fs_1.default.readFileSync(path_1.default.join(__dirname, '../../_images_index.yml'), { encoding: 'utf-8' }));
    }
    else {
        hexo.theme.config.index_images = data.index_images || [];
    }
```
默认不会加载用户定义在source/_data/image_index.yml的配置，而是先读node_modules\hexo-theme-shokaX\下的_image_index.yml，如果没有，就加载data.index_images（对应应该是source/_data/index_images.yml）。需要修改这里或者修改doc

### 注意事项

- [X] 我已确认以上事项

**Comment by skadiscarlet** [comment]
而且似乎index_images.yml和images.yml用反了？实际上是index页面用了images.yml然后post封面用了index_images.yml

**Comment by zkz098** [comment]
已修改docs。
cover和index确实是用反了，0.3.10会修复
