### ISSUE TITLE
Waline 最新评论中渲染链接错误

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#185]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/7e6298ce-0380-40f1-b2cf-7922147db8ea)
a标签渲染的链接会丢失域名（或者说多了一个`/`）
不排除为配置问题，因为其他 waline 的网站没看见有相似的问题的

### 复现步骤
发现此问题的站点：https://www.maredevi.fun/

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
有是偶发性问题的可能，但无法确认，部分生产环境站点也有类似问题

**Comment by zkz098** [comment]
需要进一步确认

**Comment by FidStyle** [comment]
@zkz098 同样遇到，复现地址：https://shokax.joytion.cn/

**Comment by FidStyle** [comment]
猜测第一个 __/__ 代表根目录，可能是转义相关的问题？ 
__/__ /2024/01/17/XXX
<==>
__example.com__ /2024/01/17/XXX

**Comment by FidStyle** [comment]
#198 solved
@zkz098
