### ISSUE TITLE
移动端长文章无法加载和显示

### ISSUE THREAD

**Issue by kagurazaka-ayano** [theme-shoka-x/hexo-theme-shokaX#191]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

长文章在手机端浏览器无法加载和显示，显示如下:
- Safari:
![IMG_0354](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/128056314/5f27e01e-05a4-48f0-ad6a-d8375915fa4d)
- edge
![IMG_0355](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/128056314/b5e09488-e0c1-4ad7-a469-a44cfcb9b75f)
- edge (in-private)
![IMG_0356](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/128056314/ec458572-1fad-4e50-8768-994b20e9b96e)
- chrome
![IMG_0357](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/128056314/478b0d9e-ba58-4a33-af54-d9bc262a4628)
- chrome (incognito)
![Screenshot 2024-01-06 at 23 15 17](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/128056314/6153082e-9dd5-4bf0-8656-c9136330e8cf)
且在即将触发该界面时加载猫猫的尾部会错位

### 复现步骤

给定长文章（~55k words + 32代码块 + 7个inline svg mermaid图(使用kroki的hexo插件生成)）, 在手机端浏览器（chrome，edge和safari皆尝试过）无法显示（效果见issue描述）

### 相关配置

hexo & node version：
```
hexo: 6.3.0
hexo-cli: 4.3.1
os: darwin 23.2.0 14.2.1

node: 21.5.0
```

[_config.shokaX.yml](https://pastebin.ubuntu.com/p/4H8Psj34mf/)
[_config.yml(省略站点信息和site-map)](https://pastebin.ubuntu.com/p/5rsf4hJNFk/)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
安卓端 Edge 116 无法复现
![af9c25a31f8c80263d7f3e52be8aee0](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/8617920c-5a1c-4865-a7cd-defd1507ee67)

**Comment by kagurazaka-ayano** [comment]
> 安卓端 Edge 116 无法复现 ![af9c25a31f8c80263d7f3e52be8aee0](https://private-user-images.githubusercontent.com/92242020/294738334-8617920c-5a1c-4865-a7cd-defd1507ee67.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDM4MTksIm5iZiI6MTcwNDYwMzUxOSwicGF0aCI6Ii85MjI0MjAyMC8yOTQ3MzgzMzQtODYxNzkyMGMtNWExYy00ODY1LWE3Y2QtZGVmZDE1MDdlZTY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA0NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWRkZjNhYzBmMDM4OThjZmI4YmU4Y2ViNGQyYjVhZGE4YThmNGRjMDUyMmY0Y2U0YzRhNzMwM2RhYTI0YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3d2B8AmGqOPC-zXuX9B3H6b5t_78MTvIdd1txh7FTJo)

奇怪那就是苹果端特有的问题？我试试用安卓机

**Comment by kagurazaka-ayano** [comment]
在mumu上尝试了一下没有问题

**Comment by kagurazaka-ayano** [comment]
奇妙。。。在mac上的iPhone模拟器尝试了也没有问题

**Comment by kagurazaka-ayano** [comment]
基本上可以排除性能的问题了~~在kindle的浏览器上可以打开~~, 等给安卓机充一下电之后看看

**Comment by kagurazaka-ayano** [comment]
安卓机可以, 鉴定为苹果物理机大失败

**Comment by zkz098** [comment]
> 安卓机可以, 鉴定为苹果物理机大失败

~~征用~~了一台 Iphone 11，虽然慢，但是能打开。
可能是偶发现象，我再看看能不能复现

**Comment by kagurazaka-ayano** [comment]
重启了一下手机居然好了（
close了
