### ISSUE TITLE
使用SXC安装的版本是 v0.3.10 而非最新 v0.3.11

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-theme-shokaX#195]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

```bash
WARN Your theme ShokaX is outdated. Current version: v0.3.10, latest version: v0.3.11
```
强迫症犯了，想直接安装最新版

### 复现步骤

SXC install shokaX -pm npm

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
@D-Sketon

**Comment by FidStyle** [comment]
@zkz098

**Comment by zkz098** [comment]
安装的版本是正确的，之前ts编译有问题所以env被锁定到0.3.10了

**Comment by FidStyle** [comment]
好的，谢谢
