### ISSUE TITLE
移除或重构 DOM 原型注入（proto.ts）

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#210]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

原型注入本质上是 jQuery 的重实现，但是目前来看，它存在如下问题：
### 方法不明确
相较于 `xxx.attr`，`xxx.setAttribute / removeAttribute / getAttribute` 更明确，`xxx.attr`需要额外思考一步来理解这是什么操作
`display`、`left`、`right`等同理

### 与 TS 相性差
现版本是使用接口合并解决的此问题，但这就意味着要维护两套类型，错误率大幅上升（）

### 为进一步迁移开路
Vue 或 React 迁移会略微更容易一点

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
fancybox会引入jQuery，没必要再实现一遍

**Comment by zkz098** [comment]
> fancybox会引入jQuery，没必要再实现一遍

但是 proto.ts 确实是把 jQuery 有关 dom 的操作重实现了一遍（）
可能 shoka 作者预留的代码没用上或者忘了这茬（）

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/a052ef71-466e-4d01-aacd-b1c83269085d)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/121ab3f8-878c-4a47-a307-12b839453228)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/7146c61d-8dcf-422f-bedd-6d347f8043c8)
看起来fancybox已经更新了n个版本了（）

**Comment by D-Sketon** [comment]
但新版的license不友好

**Comment by zkz098** [comment]
> 但新版的license不友好

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/269a2edc-14e8-4f93-b98c-a82beecfb9f4)
有点离谱（）

**Comment by zkz098** [comment]
或许可以考虑用 https://github.com/dimsemenov/PhotoSwipe 替代 fancybox

**Comment by zkz098** [comment]
在v0.4alpha2中发现原型链注入在 es module 下运行十分不顺，esbuild 无法将其注入到正确的地方（或者说因为 ESM 的异步特性这本身不太可能）

**Comment by zkz098** [comment]
这个任务交给astro迁移
