### ISSUE TITLE
config设置noplayer为true之后渲染错误

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-theme-shokaX#211]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

config设置noplayer为true之后渲染错误

有点奇怪，虽然说开启就好了（）

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/10afd23c-84f7-45bc-8e36-a649421f66ac)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
我有点过于相信 esbuild 的 tree-shaking 了（
实际上CONFIG.noPlayer不参与打包，因此player一直都没有被真正的移除掉
#212 应该修复了这个问题
