### ISSUE TITLE
增加视频全屏功能

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-theme-shokaX#214]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

好像只能使用以下配置进行视频插入？
```markdown
{% media video %}
- name: "example.mp4"
  url: https://example.com
{% endmedia %}
```

希望media标签单独对视频增加一个全屏的选项

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/8c1fd4ea-b317-4180-b716-8864dc62305f)

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
或者相关配置在哪我来改也行，我对项目结构不太熟悉

**Comment by zkz098** [comment]
https://github.com/theme-shoka-x/hexo-theme-shokaX/blob/main/scripts/tags/media.ts
media Tag 源码位置
运行时不一定在这
@FidStyle

**Comment by FidStyle** [comment]
考虑引入[hexo-tag-mmedia](https://github.com/u2sb/hexo-tag-mmedia)

作者已经弃坑了，但已测试能用。

@zkz098

**Comment by FidStyle** [comment]
且[hexo-tag-mmedia](https://github.com/u2sb/hexo-tag-mmedia)提供的[meting](https://www.u2sb.com/OpenSw/hexo-tag-mmedia/meting.html)以及[Aplayer](https://www.u2sb.com/OpenSw/hexo-tag-mmedia/aplayer.html)应该可以解决 #190 的自定义播放源的问题。

应该是没什么bug的

**Comment by zkz098** [comment]
目前来看这个插件不太适合和 ShokaX 绑定到一起，但可以作为建议依赖
可以考虑使用 DPlayer / 原生H5视频重写Media tag

**Comment by FidStyle** [comment]
确实，他这个整合比较舒服。

先close了
