### ISSUE TITLE
waline的pageview统计为0

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-theme-shokaX#215]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/5f9cd371-b9af-4a9e-83ce-b925756e002a)

leanapp中可以看到并不为0

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/bc88501a-9578-4832-8e8c-dcce08c5ce7b)

@

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
## 复现过程：

waline:
  enable: true # 是否启用
  ……
  pageview: true # 页面浏览量显示
  
##  当 waline:.enable==false 即可正常显示。

@D-Sketon

**Comment by zkz098** [comment]
waline comment和pageview使用的path并不一致，可能是引发此问题的原因
如果是本原因应当在0.4的alpha2中修复（未发布）

**Comment by D-Sketon** [comment]
多了一个/

**Comment by FidStyle** [comment]
逻辑问题：`if theme.waline.pageview && !theme.waline.enable && !theme.twikoo.enable`

alpha版本已解决
