### ISSUE TITLE
minify-html 丢失闭合标签

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#220]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/10f11bcf-db56-4b93-92e8-15a3dc29e6b2)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/7eb0ce7e-9f9a-401a-9403-79b6368fc560)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/6515521d-2059-4bba-8be0-ee264a5aa10a)
0.3.13无法复现
控制台报错看起来更像js文件被重复写入了

**Comment by D-Sketon** [comment]
0.4.0 中 `\qquad` 好像还是会导致LaTeX无法显示

**Comment by D-Sketon** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/c3f69d7d-3ab6-4a9b-99b7-3a56db228576)

**Comment by D-Sketon** [comment]
minify后丢失标签
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/0e367c21-ec05-43d8-8b03-ded8928ec353)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/a7c8e80e-85b5-406f-996d-fb435cd31b08)

**Comment by D-Sketon** [comment]
复现代码：
```js
const str = `
          <mrow>
            <mspace width="2em" />
          </mrow>
`;
const node_1 = require("@minify-html/node");
const res = node_1.minify(Buffer.from(str), {
  keep_spaces_between_attributes: true,
  keep_comments: true
}).toString()
console.log(res);
```
输出：`<mrow> <mspace width=2em> `

**Comment by zkz098** [comment]
问题普遍存在，#243 中的html下载下来也是不完整的
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/fc7556f0-6bf6-4fef-bb31-14675370a351)

**Comment by D-Sketon** [comment]
提了相关issue https://github.com/wilsonzlin/minify-html/issues/181 ， 但感觉短期内无法被解决（

**Comment by zkz098** [comment]
> 提了相关issue [wilsonzlin/minify-html#181](https://github.com/wilsonzlin/minify-html/issues/181) ， 但感觉短期内无法被解决（

是这样的，https://github.com/wilsonzlin/minify-html/issues/170 也是一个潜在问题，因为：
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/4acf48c9-1e99-440b-b3ea-5eaad9d0315e)
但这个Issue已经1个月没进展了，而且似乎从未被正式受理（）

**Comment by D-Sketon** [comment]
需要在文档中进行提示

**Comment by zkz098** [comment]
lightning 0.1.5允许使用更稳定的缩小器进行解析，我改一下文档

**Comment by zkz098** [comment]
已加文档

**Comment by zkz098** [comment]
考虑移除minify-html支持，长期来看这个库已经被放弃了

**Comment by zkz098** [comment]
[minify-html](https://github.com/wilsonzlin/minify-html) 已半年未更新，后续将移除 minify-html 支持，等待上游已经失去意义
