### ISSUE TITLE
siteRefresh 中加载音频部分忽略了 noPlayer Flag

### ISSUE THREAD

**Issue by ShellWen** [theme-shoka-x/hexo-theme-shokaX#226]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

siteRefresh 中加载音频部分忽略了 noPlayer Flag，致使在设置了 noPlayer Flag 后出现空引用异常，该问题可参考以下 commit 解决。

该问题尚未在 v0.4.0 alpha 版本中测试，但仍存在于现有的稳定版本 v0.3.13 中。

https://github.com/ShellWen/hexo-theme-shokaX/commit/29f466827a48d4c814ec5f52ada1ff3fd250237f

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
属于0.3.2的历史遗留问题，应在0.4alpha中修复

**Comment by ShellWen** [comment]
现在 alpha 发布还有一段时间，我希望能把它 cherry pick 到正式版本发布，这属于一个相对严重的问题，应当通过 hotfix 修复。

**Comment by zkz098** [comment]
已手动发布为 0.3.14
0.4alpha从通过修改打包机制从根本上修复了此问题，故此提交不合入主线
