### ISSUE TITLE
加载页面卡住，文章列表空白

### ISSUE THREAD

**Issue by YangLinzhuo** [theme-shoka-x/hexo-theme-shokaX#231]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

使用 hexo s 后查看页面会一直卡住在这个地方，一直转圈，控制台有报这些错。

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/18740976/8e65bb46-eea8-431b-9b2b-723f78a9e9ea)

用鼠标点击之后就不会再转圈，可以进入页面了，但是文章列表显示是空白的。

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/18740976/d745180d-3f8d-498c-b0d7-209d4d5dc5db)

### 复现步骤

使用 SXC 安装好依赖之后，使用默认配置，执行 hexo s 命令

### 相关配置

hexo: 7.1.1
hexo-cli: 4.3.1
os: win32 10.0.22621
node: 20.10.0
acorn: 8.10.0
ada: 2.7.2
ares: 1.20.1
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.57.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.12+quic
simdutf: 3.2.18
tz: 2023c
undici: 5.26.4
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.19
v8: 11.3.244.8-node.25
zlib: 1.2.13.1-motley

npm: 10.2.5

SXC 使用的是 pnpm 安装的
shokaX-CLI (shokaX 0.3+ ver.)
    CLI: 0.1.1 Util: 0.2.2

浏览器：

Microsoft Edge | 121.0.2277.112 (正式版本) (64 位)
修订 | c44bb51ada3168399d4dd7bc1b3939c261a4ef8f
Chromium 版本 | 121.0.6167.160
操作系统 | Windows 11 Version 22H2 (Build 22621.3007)
JavaScript | V8 12.1.14.9
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
我认为是 https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/226 的延续
通过下列代码安装 dev 版试试：
```bash
pnpm add hexo-theme-shokax@dev
pnpm add js-yaml @waline/client algoliasearch esbuild hexo-fs hexo-pagination hexo-renderer-multi-next-markdown-it hexo-renderer-pug hexo-renderer-stylus hexo-util instantsearch.js lozad unlazy pangu quicklink theme-shokax-anime  theme-shokax-pjax twikoo vue
```

**Comment by YangLinzhuo** [comment]
> 我认为是 #226 的延续 通过下列代码安装 dev 版试试：
> 
> ```shell
> pnpm add hexo-theme-shokax@dev
> pnpm add js-yaml @waline/client@3.0.0-alpha.11 algoliasearch esbuild hexo-fs hexo-pagination hexo-renderer-multi-next-markdown-it hexo-renderer-pug hexo-renderer-stylus hexo-util instantsearch.js lozad unlazy pangu quicklink theme-shokax-anime  theme-shokax-pjax twikoo vue
> ```

按照这个可以正常显示了👍

**Comment by zkz098** [comment]
> > 我认为是 #226 的延续 通过下列代码安装 dev 版试试：
> > ```shell
> > pnpm add hexo-theme-shokax@dev
> > pnpm add js-yaml @waline/client@3.0.0-alpha.11 algoliasearch esbuild hexo-fs hexo-pagination hexo-renderer-multi-next-markdown-it hexo-renderer-pug hexo-renderer-stylus hexo-util instantsearch.js lozad unlazy pangu quicklink theme-shokax-anime  theme-shokax-pjax twikoo vue
> > ```
> 
> 按照这个可以正常显示了👍

安装最新版 SXC 之后安装 0.4 应该就正常了
可能需要等 npmmirror 刷新缓存

**Comment by YangLinzhuo** [comment]
好的🆗
