### ISSUE TITLE
0.4.1部分问题：waline显示异常 & video标签无法显示

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-theme-shokaX#236]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/e653be69-79ff-486d-8ea5-78dd3aeb5f8b)

### waline显示异常

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/e5e17c3d-7d2d-438c-b853-b2a96823ceee)

@zkz098 

### 复现步骤

0.3.12升级0.4.1

### 相关配置

shokaX-CLI (shokaX 0.4+ ver.)

hexo-theme-shokax@0.4.1

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
同时tag似乎没有显示（没有报错）
```markdown
{% media video %}
- name: "example.mp4"
  url: https://example.com/example.mp4
{% endmedia %}
```

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/85717c67-bade-4b03-b9b2-f1593b778c55)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/3e4c1598-b5d2-4817-895e-44ffadf41b0b)
浏览量应该是上游问题，waline 文档都这样（）

最新评论那个属于 waline 改了 API 但没有事先通知，types类型也对不上，comments里面多套了一层data，有点怪

media tag依赖于player运行，Modules.player如果为false就会不显示

**Comment by FidStyle** [comment]
media在启用player后解决。
waline我看看怎么个事

**Comment by zkz098** [comment]
目前已强行修复
此 Issue 需要保持开启状态，直到确认是否为上游问题

**Comment by FidStyle** [comment]
0.4.2最新评论正常，无法显示阅读次数。
之前部署的0.3.13版本是可以正常使用的
@zkz098

**Comment by zkz098** [comment]
> 0.4.2最新评论正常，无法显示阅读次数。 之前部署的0.3.13版本是可以正常使用的，能够正常显示阅读次数 @zkz098

0.4开始使用打包的waline加载（即为waline文档中[object Object]的那个模块）
0.4之前用的UMD引入，所以和waline文档中的后者一样

**Comment by zkz098** [comment]
感觉是waline的问题，因为他们自己的文档都[object Object]了（）

**Comment by FidStyle** [comment]
是这样，唯一正常的是不带data-path参数的调用
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/24635e58-29ae-4efe-a39f-ca3225748141)

**Comment by FidStyle** [comment]
https://github.com/walinejs/waline/issues/2207
@zkz098

**Comment by FidStyle** [comment]
close with #250

**Comment by FidStyle** [comment]
测试各功能均已正常
