### ISSUE TITLE
hexo-lightning-minify 错误转换外链图片

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#239]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/2993a6c1-de90-4a37-aaec-4000cd050f04)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/25d139cb-4999-4e01-a5ec-b2d60a3e167c)

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
0.1.4应该修好了，现在以http开头的图片会被排除
