### ISSUE TITLE
shokaX 配置 twikoo 评论系统，运行报错 getRecentComments  not a function，评论也没出来，twikoo是docker私有部署，没有问题

### ISSUE THREAD

**Issue by Anixuil** [theme-shoka-x/hexo-theme-shokaX#254]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

![QQ截图20240310184046](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49489323/fa62c2a1-4994-44e5-b5a1-aff0206f0db3)
![QQ截图20240310184302](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49489323/6e96d924-205a-4205-a5c3-9744f4c34b16)
![QQ截图20240310184310](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49489323/1dbaeefa-5b68-496d-a78c-5f795b4c9cfc)
![QQ截图20240310184359](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49489323/08a438c2-ed8b-4dd1-9f20-68e9d3eb79c0)

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
@D-Sketon

**Comment by D-Sketon** [comment]
twikoo 不支持 import 的方式引入
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/08e6f18a-f52a-4c92-a7fb-ed89a7c27b13)

**Comment by Anixuil** [comment]
> twikoo 不支持 import 的方式引入 ![image](https://private-user-images.githubusercontent.com/49871906/311523754-08e6f18a-f52a-4c92-a7fb-ed89a7c27b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzgyOTAsIm5iZiI6MTcxMDEzNzk5MCwicGF0aCI6Ii80OTg3MTkwNi8zMTE1MjM3NTQtMDhlNmYxOGEtZjUyYS00YzkyLWE3ZmItZWQ4OWE3YzI3YjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MzI3OWVmNGE4MTYyMzMzOTIyOGZmZjI1MzJkYjQxYmI5MzNkM2ZiMGViNWMxYjlhMDdiZThjNmMwNDlhNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tw27DDrRNiaND0dBYmEVDGo4RxOT3r2JFr0JPljH3AQ)

我是用SXC 初始化的项目，不是在theme里放入的，这种情况下我该如何解决这个问题，我拉下这个仓库的源码看了找到了这个地方

**Comment by D-Sketon** [comment]
`node_modules/hexo-theme-shokax/source/js/_app/components` 中
```js
import twikoo from 'twikoo'
```
改为
```js
import * as twikoo from 'twikoo'
```

**Comment by Anixuil** [comment]
> `node_modules/hexo-theme-shokax/source/js/_app/components/tcomments.ts` 中
> 
> ```js
> import twikoo from 'twikoo'
> ```
> 
> 改为
> 
> ```js
> import * as twikoo from 'twikoo'
> ```

谢谢，解决了
