### ISSUE TITLE
Prism‘s-diff language definition未配置

### ISSUE THREAD

**Issue by EarendelH** [theme-shoka-x/hexo-theme-shokaX#255]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.
我在进行SXC install shokax后的所有hexo d 都会报此错误，且在shoka的原仓库下发现有人提出这个issue，说是更改package.json即可，但不知应该如何修改

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/2ca77e9a-8cc2-48cb-a044-135e387db3fe)
目前来看直接忽略即可，没有其他错误应该能够正常使用，个人使用中没有发现相关错误影响
@EarendelH

**Comment by FidStyle** [comment]
一般来说只要没有ERROR就行，WARN还有这个Prism的问题就让他去吧（）
