### ISSUE TITLE
note 提醒塊無法正常顯示

### ISSUE THREAD

**Issue by ThanatosDi** [theme-shoka-x/hexo-theme-shokaX#257]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [ ] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

當使用 note 提醒塊語法時在前端無法正常渲染
```
:::warning
測試 warning 提醒
:::
```

在前端顯示為 
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/12424898/e01f7655-c73a-4738-91f8-49034dc4cf7f)

正常應顯示為
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/12424898/63d14d89-a70b-4f72-bccf-1591b4eee0ec)

### 相关配置

```tree
blog
├── @algolia/client-search@4.22.1
├── @waline/client@3.0.1
├── algoliasearch@4.22.1
├── esbuild@0.20.0
├── hexo-algoliasearch@2.0.1
├── hexo-feed@1.1.2
├── hexo-fs@4.1.1
├── hexo-lightning-minify@0.1.5
├── hexo-pagination@3.0.0
├── hexo-renderer-multi-next-markdown-it@0.2.1
├── hexo-renderer-pug@3.0.0
├── hexo-theme-shokax@0.4.2
├── hexo-util@3.2.0
├── hexo@7.0.0
├── instantsearch.js@4.64.2
├── js-yaml@4.1.0
├── mouse-firework@0.0.5
├── quicklink@2.3.0
├── shokax-cli@0.1.0
├── theme-shokax-anime@0.0.6
├── theme-shokax-pjax@0.0.3
├── twikoo@1.6.31
├── unlazy@0.10.4
└── vue@3.4.15
```

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/0e2adee7-aad0-47ef-b34e-cc25643b027a)
无法复现

**Comment by ThanatosDi** [comment]
在本地開發環境的時候會噴出大量 404 錯誤
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/12424898/16ce4030-287d-47ca-8984-986df5ce9640)

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/12424898/b1e30256-1f9d-47e7-bc55-681f48384be4)

**Comment by D-Sketon** [comment]
有些奇怪，请问其他文章也会大量报404错误吗？我这里使用给的配置仍然无法复现，

**Comment by ThanatosDi** [comment]
目前測試的結果是
- 首頁不會發生大量 404 錯誤
- 在畫面中點入至文章頁面沒有錯誤，但在文章頁面重新整理就會大量噴錯誤

可是還是沒辦法正常顯示 note block 😭

**Comment by ThanatosDi** [comment]
> 重新 SXC 試試呢，或者再新創一個環境 換用 npm 安裝：
> 
> ```shell
> npm -g install hexo-cli
> hexo init
> npm -g install shokax-cli
> SXC install shokaX -pm npm # 嘗試指定npm。
> ```
> 
> 複製原組態到新環境即可，以排除依賴問題

開新環境執行該內容後就正常顯示了
