### ISSUE TITLE
是否可以在copy时设置字数限额并添加版权信息和协议？而简单复制一到两行则复制时不添加版权信息。

### ISSUE THREAD

**Issue by MorIo24** [theme-shoka-x/hexo-theme-shokaX#262]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

增加一个开关来设置copy时的提示注意版权信息，可以设置字数限额，例如复制超过100个字时携带版权信息，而仅仅复制代码块中的内容无需携带版权信息。

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
其实是有的，只是默认字数太小导致多数情况下都没用（
后续版本会允许自定义
