### ISSUE TITLE
如果安装了yarn，hexo init后再SXC install shokaX，报错

### ISSUE THREAD

**Issue by YeexiaoZheng** [theme-shoka-x/hexo-theme-shokaX#265]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/97672942/639c596b-08b3-499f-8ef0-16a997b00f7d)

### 复现步骤

安装npm10.5.2，并安装了yarn，然后在一个仓库hexo init，再执行SXC install shokaX，它会INFO  Using package manager: yarn
而如果我不执行hexo init，单执行SXC install shokaX它会INFO  Using package manager: npm

### 相关配置

hexo: 7.0.0
hexo-cli: 4.3.2
os: win32 10.0.22631 undefined
node: 20.11.1

### 注意事项

- [X] 我已确认以上事项

**Comment by YeexiaoZheng** [comment]
uninstall yarn后解决此问题

**Comment by D-Sketon** [comment]
hexo是优先使用yarn安装的

**Comment by D-Sketon** [comment]
https://github.com/wilsonzlin/minify-html/issues/180

**Comment by YeexiaoZheng** [comment]
懂了 所以是yarn本身的问题

**Comment by D-Sketon** [comment]
@YeexiaoZheng 
https://github.com/theme-shoka-x/hexo-theme-shokaX/blob/main/_config.yml#L1-L1
