### ISSUE TITLE
終端機出現以下訊息：sinaimg blocked all request from outside website,so don't use this format

### ISSUE THREAD

**Issue by LiuWaiting203** [theme-shoka-x/hexo-theme-shokaX#279]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

无法判断

### 问题描述

當我使用主題設置時，在 `/_config.shokax.yml` 下設置自己主題風格的時候，終端機出現以下訊息
`sinaimg blocked all request from outside website,so don't use this format`

### 复现步骤

有重新把  `/_config.shokax.yml` 的內容刪除後，再重新設置一次，之後用 `hexo clean` 與 `hexo server` 之後還是有出現這個訊息

### 相关配置

開發工具：Visual Studio Code (2024)
網頁：Brave 1.66.118 Chromium: 125.0.6422.147 
Hexo : 4.3.2
Node.js v20.13.1
Npm v10.5.2

### 注意事项

- [X] 我已确认以上事项

**Comment by LiuWaiting203** [comment]
順帶一提終端機也不斷提示說 `Plugin load failed: hexo-renderer-markdown-it`

**Comment by LiuWaiting203** [comment]
> ### 在开始之前......
> * [x]  我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
> * [x]  我确认最新版尚未修复此问题，且此前没有人提出过此问题
> * [x]  为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`
> 
> ### 问题发生位置
> 无法判断
> 
> ### 问题描述
> 當我使用主題設置時，在 `/_config.shokax.yml` 下設置自己主題風格的時候，終端機出現以下訊息 `sinaimg blocked all request from outside website,so don't use this format`
> 
> ### 复现步骤
> 有重新把 `/_config.shokax.yml` 的內容刪除後，再重新設置一次，之後用 `hexo clean` 與 `hexo server` 之後還是有出現這個訊息
> 
> ### 相关配置
> 開發工具：Visual Studio Code (2024) 網頁：Brave 1.66.118 Chromium: 125.0.6422.147 Hexo : 4.3.2 Node.js v20.13.1 Npm v10.5.2
> 
> ### 注意事项
> * [x]  我已确认以上事项

> 順帶一提終端機也不斷提示說 Plugin load failed: hexo-renderer-markdown-it

這些已解決，在這 [Issue](https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/142) 找到解答 

現在是如何切換語言，目前我一直在日、英、繁中、簡中不斷切換

**Comment by FidStyle** [comment]
> 現在是如何切換語言，目前我一直在日、英、繁中、簡中不斷切換
不太明白您的问题在哪，建议新开一个Issue解决。这个先close了

**Comment by FidStyle** [comment]
> 現在是如何切換語言，目前我一直在日、英、繁中、簡中不斷切換
不太明白您的问题在哪，建议新开一个Issue解决。这个先close了
