### ISSUE TITLE
地區語言不斷切換，無法固定地區

### ISSUE THREAD

**Issue by LiuWaiting203** [theme-shoka-x/hexo-theme-shokaX#280]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

Hexo 中的地區語言不斷切換，無法固定地區語言： `zh-TW` 也就是繁中
有時會被切換至日語、英語及簡中
![lang](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/127477317/7d459a28-0cd0-44f7-b618-8a13bc9c4ed9)

表格的樣式無法正常顯示
![table](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/127477317/ebaf1cdb-ffe5-463e-b73d-533f0d77a1f5)

部屬至 Github 但 Avatar 卻是死圖，在本機上看卻是正常的
Github:
![git](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/127477317/5d597005-c952-4f09-8a5b-703791eb5722)
Localhost:
![local](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/127477317/b0647c65-4454-4b15-9ab6-b724a4f5fa5b)

### 复现步骤

將 `_config.yml` 裡的 language 設置成 `zh-TW` 
把 node_modules 目錄下的 shokaX 根目錄裡面的語言包除了 `zh-TW` 外其他都替換名字

### 相关配置

Hexo: 7.0.0
Node: 20.13.1
網頁: Brave 最新版

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
图片404问题请尝试重复运行两次 `hexo g` 后再运行 `hexo d` 进行部署

**Comment by zkz098** [comment]
无法复现
如果可能请将运行环境压缩后发送至 zkz20081204@126.com
