### ISSUE TITLE
建了images_index.ym但是首页轮播图并没有被替换

### ISSUE THREAD

**Issue by SuperJeason** [theme-shoka-x/hexo-theme-shokaX#296]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

大佬你好，冒昧打扰您一下，在使用shokaX主题时，根据大佬的教程文档在source/_data下建立了images_index.yml文件，但是首页轮播图并没有变化，主题文件夹下我并没有找到_images_index.yml，请教一下可能是哪里的问题，大佬可以帮忙看看首页轮播图这个图片储存在哪里嘛(SuperJeason.github.io)

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
> 自0.3.7版本开始，ShokaX 允许主页和文章使用不同的图片源：
以下文件中以`_`开头的为主题文件夹下，其他均为`source/_data`目录下：
> 
> - `images_index.yml`为首页图片源文件，如果主题文件夹下存在`_images_index.yml`，则会使用主题文件夹下的文件，否则使用`source/_data/images_index.yml`
> - `images.yml`为通用图片源文件，作为首页的后备图片源和文章的图片源。如果未找到`images.yml`，则会使用主题文件夹下的`_images.yml`

主题没有初始化_images_index.yml，但是可以自己建立一个文件保证功能正常。

正常来说如果静态轮播图性能回更好，在`_config.shokax.yml`配置即可：
  ```yaml
  homeConfig:
    gradient: false # 使用CSS渐变作为文章封面
    # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载 TODO
    fixedCover: "/Your/Path/To.webp" # 主页面cover(为空则使用bing随机图片)
  ```

但是你的原因是因为
`https://7ed.net/bing/api`这个bing随机图api在不同ip环境下可能会失效的原因

检查以下两项：
  1. 主题文件夹下的_images.yml是否进行了配置，如果有是否超过6张图片，是否为有效地址。
  2. homeConfig.fixedCover是否配置，看看你的homeConfig配置项。
当homeConfig.fixedCover为空时会尝试使用_images.yml配置轮播，当_images.yml无效或不可用时会使用不稳定的`https://7ed.net/bing/api`随机bing图片轮播api。

api的不稳定导致以下两种情况的出现：
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/71cc5aa8-90a0-4e71-be4b-de5a915eb68f)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/49d50670-ee5e-4e47-9738-f497af658b92)

解决方案：
1. 配置主题文件夹下的_images.yml，保证存在大于等于6张图片的有效地址。
2. 配置homeConfig.fixedCover使用更高效的静态首页图

**Comment by SuperJeason** [comment]
> > 自0.3.7版本开始，ShokaX 允许主页和文章使用不同的图片源：
> > 以下文件中以`_`开头的为主题文件夹下，其他均为`source/_data`目录下：
> > 
> > * `images_index.yml`为首页图片源文件，如果主题文件夹下存在`_images_index.yml`，则会使用主题文件夹下的文件，否则使用`source/_data/images_index.yml`
> > * `images.yml`为通用图片源文件，作为首页的后备图片源和文章的图片源。如果未找到`images.yml`，则会使用主题文件夹下的`_images.yml`
> 
> 主题没有初始化_images_index.yml，但是可以自己建立一个文件保证功能正常。
> 
> 正常来说如果静态轮播图性能回更好，在`_config.shokax.yml`配置即可：
> 
> ```yaml
> homeConfig:
>   gradient: false # 使用CSS渐变作为文章封面
>   # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载 TODO
>   fixedCover: "/Your/Path/To.webp" # 主页面cover(为空则使用bing随机图片)
> ```
> 
> 但是你的原因是因为 `https://7ed.net/bing/api`这个bing随机图api在不同ip环境下可能会失效的原因
> 
> 检查以下两项：
> 
> 1. 主题文件夹下的_images.yml是否进行了配置，如果有是否超过6张图片，是否为有效地址。
> 2. homeConfig.fixedCover是否配置，看看你的homeConfig配置项。
>    当homeConfig.fixedCover为空时会尝试使用_images.yml配置轮播，当_images.yml无效或不可用时会使用不稳定的`https://7ed.net/bing/api`随机bing图片轮播api。
> 
> api的不稳定导致以下两种情况的出现： ![image](https://private-user-images.githubusercontent.com/115857087/344053692-71cc5aa8-90a0-4e71-be4b-de5a915eb68f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzc0MTUsIm5iZiI6MTcxOTU3NzExNSwicGF0aCI6Ii8xMTU4NTcwODcvMzQ0MDUzNjkyLTcxY2M1YWE4LTkwYTAtNGU3MS1iZTRiLWRlNWE5MTVlYjY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjE4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzNmODgyM2NmZjQ0NzhjZmJkMWI3MDE0YTQyMjZkOGVhYTU3OGUyNGI5NmRiNjhlNDFjZDQwYmZjNWU1MGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o_S67AYLVvb8386ZN0YdBfmLd--Rfb01VWdi5QlG2jI) ![image](https://private-user-images.githubusercontent.com/115857087/344059863-49d50670-ee5e-4e47-9738-f497af658b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzc0MTUsIm5iZiI6MTcxOTU3NzExNSwicGF0aCI6Ii8xMTU4NTcwODcvMzQ0MDU5ODYzLTQ5ZDUwNjcwLWVlNWUtNGU0Ny05NzM4LWY0OTdhZjY1OGI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjE4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDYwOWI2MmFiYzk1OGZiZTI2NWM3OGQ3NTk5OTM5NTRmMTI4YTBkNjE1NTExOWJlOWZkOGYzOGU1OWJlYTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.prY-Ov9-KJpHSq7m22iZkWmDMh52FCuW23jDAyhtkFM)
> 
> 解决方案：
> 
> 1. 配置主题文件夹下的_images.yml，保证存在大于等于6张图片的有效地址。
> 2. 配置homeConfig.fixedCover使用更高效的静态首页图

非常感谢大佬的回复，这两步骤我都做了，homeConfig.fixedCover这个我填的单图片地址但是不生效，_images.yml这里面也换了新的图床链接，首页图片还是随机生成的，很奇怪的，还有就是本地测试头像都可以正常显示，但是deploy后就不显示了，这是什么问题呢

**Comment by FidStyle** [comment]
可能跟你的文件路径有关，本地和部署后的路径识别不一致。方便给一下homeConfig.fixedCover的地址吗

**Comment by SuperJeason** [comment]
> 可能跟你的文件路径有关，本地和部署后的路径识别不一致。方便给一下homeConfig.fixedCover的地址吗

https://i.111666.best/image/C2RYcE6LHiSbKr0iavxGA9.jpg   刚刚又试了下，这个本地封面切换成功了，但是deploy后还是随机的

**Comment by FidStyle** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/7ac39442-c984-4336-b4e8-e35d37697d78)
缓存问题吧，清楚缓存强制刷新试试

**Comment by FidStyle** [comment]
头像问题建议F12对应检查是否存在相关文件

**Comment by zkz098** [comment]
头像问题系lightning特性，跑两次hexo g后部署即可解决

**Comment by SuperJeason** [comment]
> 头像问题建议F12对应检查是否存在相关文件

好的非常感谢大佬耐心回答
