### ISSUE TITLE
webcache.cn已经不再提供当前版本的fancybox.css

### ISSUE THREAD

**Issue by TrueRou** [theme-shoka-x/hexo-theme-shokaX#297]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

https://npm.webcache.cn/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
返回403 Forbidden, 可能导致fancybox无法加载, 文章中的图片点击后样式出现问题

### 注意事项

- [X] 我已确认以上事项

**Comment by FidStyle** [comment]
近期各cdn停止维护，目前可用：
https://fastly.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
https://unpkg.com/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
https://npm.elemecdn.com/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css

目前可用性(速度) npm.elemecdn.com > unpkg.com > fastly.jsdelivr.net
其中npm.elemecdn.com可能不太全面，具体表现为：
同时访问三者的npm包：`/jquery@3/dist/jquery.min.js`，只有npm.elemecdn.com返回的是`jQuery v3.5.1` ，其余均为`jQuery v3.7.1`

@zkz098 @D-Sketon 是否有必要替换cdn

**Comment by FidStyle** [comment]
npm.webcache.cn不稳定，可能跟dns缓存有关（猜）
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/3e3093d5-111c-4d52-a93e-6bc3fad2d073)
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/05b07e55-4d3e-4b44-b511-60a5b5c3d234)

**Comment by zkz098** [comment]
目前来看应该fancybox换photoswipe然后本地引入，现版本这个fancybox已经太老了，维护的价值不大。ShokaX 0.4.6 支持 esbuild 动态捆绑 CSS，所以photoswipe不需要走CDN

**Comment by zkz098** [comment]
> npm.webcache.cn不稳定，可能跟dns缓存有关（猜） ![image](https://private-user-images.githubusercontent.com/115857087/344511236-3e3093d5-111c-4d52-a93e-6bc3fad2d073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTkyNDEsIm5iZiI6MTcxOTc5ODk0MSwicGF0aCI6Ii8xMTU4NTcwODcvMzQ0NTExMjM2LTNlMzA5M2Q1LTExMWMtNGQ1Mi1hOTNlLTZiYzNmYWQyZDA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMTU1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTQzNWQxZTA2OTI5NWRmNGUwZTE5NGVkZTk3M2U5OTE5MmVkOTU5YTgzMjM2ZmEwZmEwY2Y0NzkzYjBmNmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5plPHTYFIgM2Q3Hqwj9ksCW3FqywQy3_MBjQaN0cULY) ![image](https://private-user-images.githubusercontent.com/115857087/344511100-05b07e55-4d3e-4b44-b511-60a5b5c3d234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTkyNDEsIm5iZiI6MTcxOTc5ODk0MSwicGF0aCI6Ii8xMTU4NTcwODcvMzQ0NTExMTAwLTA1YjA3ZTU1LTRkM2UtNGI0NC1iNTExLTYwYTViNWMzZDIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMTU1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmQ1Y2RmOGM0YTg0NTAyYzllNjc4YWYwOTI0MmU0YWRjNzQyZGVmMTliOTI3Y2M3YjkzZTg3YTA4ZTM5OTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6u3N9laP0l8hRRpKMakNVhUZJRntoP72WE_6fwUI0W8)

拿itdog扫了一下，国内的所有节点都是403但国外正常，可能暂时屏蔽国内访问了

**Comment by FidStyle** [comment]
基本确定npm.webcache.cn限制referer了，乐
```python
import requests

def check_url_accessibility(url, referer=None):
    headers = {}
    if referer:
        headers['Referer'] = referer
    try:
        response = requests.head(url, headers=headers)
        if response.status_code == 200:
            return True
        else:
            return False
    except requests.RequestException as e:
        print(f"Error accessing {url}: {e}")
        return False

# Example usage
url = "https://npm.webcache.cn/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"
referer = "https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/297"

# Check URL accessibility with Referer
is_accessible_with_referer = check_url_accessibility(url, referer)
print(f"URL {url} is accessible with Referer {referer}: {is_accessible_with_referer}")

# Check URL accessibility without Referer
is_accessible_without_referer = check_url_accessibility(url)
print(f"URL {url} is accessible without Referer: {is_accessible_without_referer}")
```
自行测试一下，我这是有区别的
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/115857087/89fd347e-c2ca-41da-aac1-155df97c9914)

**Comment by zkz098** [comment]
> 基本确定npm.webcache.cn限制referer了，乐
> 
> ```python
> import requests
> 
> def check_url_accessibility(url, referer=None):
>     headers = {}
>     if referer:
>         headers['Referer'] = referer
>     try:
>         response = requests.head(url, headers=headers)
>         if response.status_code == 200:
>             return True
>         else:
>             return False
>     except requests.RequestException as e:
>         print(f"Error accessing {url}: {e}")
>         return False
> 
> # Example usage
> url = "https://npm.webcache.cn/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"
> referer = "https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/297"
> 
> # Check URL accessibility with Referer
> is_accessible_with_referer = check_url_accessibility(url, referer)
> print(f"URL {url} is accessible with Referer {referer}: {is_accessible_with_referer}")
> 
> # Check URL accessibility without Referer
> is_accessible_without_referer = check_url_accessibility(url)
> print(f"URL {url} is accessible without Referer: {is_accessible_without_referer}")
> ```
> 
> 自行测试一下，我这是有区别的 ![image](https://private-user-images.githubusercontent.com/115857087/344513385-89fd347e-c2ca-41da-aac1-155df97c9914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTk3ODcsIm5iZiI6MTcxOTc5OTQ4NywicGF0aCI6Ii8xMTU4NTcwODcvMzQ0NTEzMzg1LTg5ZmQzNDdlLWMyY2EtNDFkYS1hYWMxLTE1NWRmOTdjOTkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMjA0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FmNGRhYjNjNWU1MGJlNDkyYzZmNmYwZjkyYjk3YmZjNGIxNzJmODRjMjk1MGUzZDNjMmI2MDI1YThlZmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1RY-n1NPpIkXwkTeqOpUVGYaWeHRPPmNqE4i2qfoP4I)

是这样的
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/8a265700-2a8d-46c6-a949-f9e850116a90)

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/ca977b63-a8f0-40c2-a126-08d3a4d41f30)
盲猜配置失误，因为当Referer直接为`https://github.com`时也无法访问，但`https://github.com/`是正常的（

**Comment by FidStyle** [comment]
> ![image](https://private-user-images.githubusercontent.com/92242020/344514052-ca977b63-a8f0-40c2-a126-08d3a4d41f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDA1NDQsIm5iZiI6MTcxOTgwMDI0NCwicGF0aCI6Ii85MjI0MjAyMC8zNDQ1MTQwNTItY2E5NzdiNjMtYThmMC00MGMyLWExMjYtMDhkM2E0ZDQxZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAyMTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNDBmYTI3NzZmMGMwZGU3MWMwZTk5MjE0MTFiYjFmNDQzZGM3Njc2MzAwNTgwOTI4N2M4ZTkyOTQwMTc4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NleXQZ51vw12CMv_04p-55wvxECiKQFDEVfTTvBBVuA) 盲猜配置失误，因为当Referer直接为`https://github.com`时也无法访问，但`https://github.com/`是正常的（

确实，我用插件测试了，奇怪

**Comment by zkz098** [comment]
现在问题在于
如果换成 Photoswipe 其实有一定复杂度，实现需要时间，但能治根
如果切换CDN:
npm.elemecdn.com 是私有CDN，换过去之后长期稳定和安全风险挺高的
剩下那两个加载速度有点抽象了，unpkg走cloudflare确实慢，jsd已经爆过N次雷了
我看这个问题还存在，稍后我联系一下webcache方面确认一下是故意的还是不小心的（）

**Comment by Francklin** [comment]
已邮件回复。也可在此粘贴下可复现问题的案例链接，我好快速测试，谢谢！

**Comment by D-Sketon** [comment]
Photoswipe 正在尝试迁移，但其无法完全覆盖当前fancybox的所有功能，且现在遇到了一些bug
还是等到0.5后稳定了些再迁移吧，迁移后也需要大量测试

**Comment by zkz098** [comment]
> 已邮件回复。也可在此粘贴下可复现问题的案例链接，我好快速测试，谢谢！

应该是用户侧对 webcache 传了 `no-referrer` 策略，和 webcache 本身的访问限制没有关系，抱歉
建议您在使用限制中加上referrer为空也会拦截这条，现在版本的使用限制是没有的

**Comment by zkz098** [comment]
> Photoswipe 正在尝试迁移，但其无法完全覆盖当前fancybox的所有功能，且现在遇到了一些bug 还是等到0.5后稳定了些再迁移吧，迁移后也需要大量测试

0.5估计会等到 Astro 版本能发布0.0.1之后再考虑，Hexo版本接下来一段时间就以修Bug为主了

**Comment by Francklin** [comment]
> > 已邮件回复。也可在此粘贴下可复现问题的案例链接，我好快速测试，谢谢！
> 
> 应该是用户侧对 webcache 传了 `no-referrer` 策略，和 webcache 本身的访问限制没有关系，抱歉 ~建议您在使用限制中加上referrer为空也会拦截这条，现在版本的使用限制是没有的~
> 
> 建议您还是放行 referrer 为空的请求，现在各个网站开始启用 SRI 了，SRI 一般会和 `crossorigin="anonymous"` 配合使用，所以发的请求 referrer 都为空，拦截 referrer 为空和禁用 SRI 是差不多的



> > 已邮件回复。也可在此粘贴下可复现问题的案例链接，我好快速测试，谢谢！
> 
> 应该是用户侧对 webcache 传了 `no-referrer` 策略，和 webcache 本身的访问限制没有关系，抱歉 ~建议您在使用限制中加上referrer为空也会拦截这条，现在版本的使用限制是没有的~
> 
> 建议您还是放行 referrer 为空的请求，现在各个网站开始启用 SRI 了，SRI 一般会和 `crossorigin="anonymous"` 配合使用，所以发的请求 referrer 都为空，拦截 referrer 为空和禁用 SRI 是差不多的

我我看下怎么解决这个问题。

**Comment by Francklin** [comment]
经测试，SRI 和 crossorigin="anonymous" 配合使用时，默认情况下不会传输空referrer头，可正常使用。空referrer是站长设置了meta头限制

**Comment by Francklin** [comment]
也不要在script标签上添加referrerpolicy属性
