### ISSUE TITLE
shokaX将会更新的功能列表

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#3]
如题,本issues作为本项目的代办列表
- [x] https://github.com/amehime/hexo-theme-shoka/issues/50
- [x] https://github.com/amehime/hexo-theme-shoka/issues/59
- [x] https://white-album.top/computer-science/hexo/shoka/outime/
- [ ] 将加载动画以js canvas实现
- [x] 插件系统(长期计划)
- [ ] 异步化js(长期计划)

**Comment by duchenpaul** [comment]
原版的音乐播放器似乎不可用了, 这个可能修复么?

**Comment by zkz098** [comment]
可以修复,但是需要一个新的音乐API,老的API已经502了
@duchenpaul

**Comment by zkz098** [comment]
找到一个替代的API: https://api.injahow.cn/meting/ 稍后替换一下

**Comment by zkz098** [comment]
@duchenpaul 0.1.1版本已修复此问题

**Comment by MapleNe** [comment]
在移动移动端中，使用多dropbox菜单会被侧边栏的控件挡住且无法下滑

**Comment by zkz098** [comment]
> 在移动移动端中，使用多dropbox菜单会被侧边栏的控件挡住且无法下滑

建议new一个issue 没有图片比较难理解具体问题

**Comment by MapleNe** [comment]
> 

子菜单被挡住，且无法下滑

**Comment by zkz098** [comment]
此issues的任务已结束，剩余部分已合入其他开发计划
