### ISSUE TITLE
Iconfont 链接失效

### ISSUE THREAD

**Issue by Nightingale0504** [theme-shoka-x/hexo-theme-shokaX#307]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

![Snipaste_Windows_NT-RHODESISLAND-Logos0905-iconfont-阿里巴巴矢量图标库 - Google Chrome-2024-07-20_04-03-42](https://github.com/user-attachments/assets/eebe9341-e754-49ce-ad54-c1082b1be724)
如图

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
cc @FidStyle

**Comment by FidStyle** [comment]
https://www.iconfont.cn/invite?type=project&token=JZNyYtPHBsu67t0E#邀请你加入「shoka」
@Nightingale0504 
需要更新链接，我改下文档
