### ISSUE TITLE
无法切换显示语言

### ISSUE THREAD

**Issue by Nightingale0504** [theme-shoka-x/hexo-theme-shokaX#308]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

使用 hexo-shokaX 在本地测试时发现：每次重新hexo s启动服务器时，显示的语言都会是从简中、英语、日语中随机选择，我如何才可以固定 hexo-shokaX 的显示语言

### 相关配置

hexo: 7.3.0
hexo-cli: 4.3.2
os: win32 10.0.26227 undefined
node: 22.4.1
chrome: 126.0.6478.183

### 注意事项

- [x] 我已确认以上事项

**Comment by zkz098** [comment]
cc @D-Sketon 
和 #280 症状类似，目前尚未确定原因
如果可能您可以将 hexo 环境打包发送至 admin#shokax.top (#替换为@) 协助我们排查

**Comment by D-Sketon** [comment]
从来没有遇到过（

**Comment by yyuuz** [comment]
language: zh-cn改为zh-CN呢 我是这样解决的

**Comment by Nightingale0504** [comment]
解决了，谢谢 @yyuuz

**Comment by Nightingale0504** [comment]
解决了，谢谢 @yyuuz
