### ISSUE TITLE
是否可以适配codeblock的标签插件

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#31]
### 建议描述

诸如这样的：
```yaml
{% codeblock [title] [lang:language] [url] [link text] [additional options] %}
code snippet
{% endcodeblock %}
```

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
目前如果实现和shokaX自带代码高亮一致效果，代码会很奇怪(基本上就是CV了一遍渲染器)
近期shokaX会尝试修改一下代码高亮相关代码，codeblock支持会在这个之后

**Comment by D-Sketon** [comment]
查询进度

**Comment by zkz098** [comment]
进度不是很顺利，因为修改代码高亮的尝试炸掉了
目前正在把这个功能做成插件

**Comment by D-Sketon** [comment]
啊这，需要什么帮助吗()

**Comment by zkz098** [comment]
> 啊这，需要什么帮助吗()

目前不需要，主要是在代码高亮拆分上浪费了太多时间()

**Comment by zkz098** [comment]
有点麻了，这个功能先改成 good first issue ，最近actions的问题还没解决（）

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/67a9b5af-32e1-4108-b67f-436d52bbd758)
mermaid的加载问题也许是prism提前捕获了mermaid这一token，并阻止了它传递到mermaid渲染器
但代码上来说覆盖的可能性更大()

**Comment by YangLinzhuo** [comment]
https://blog.liq2.com/article/ff29002e 看这个博主说的，好像 mermaid 没有被识别，改成 Mermaid 或者 mermaid2 就可以了(
