### ISSUE TITLE
请支持Element UI

### ISSUE THREAD

**Issue by Nightingale0504** [theme-shoka-x/hexo-theme-shokaX#310]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

由于shokaX基于vue3，因此可以支持element ui，能否将开启element ui加入主题配置？

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
事实上，shokaX v0.4后已经移除了Vue的依赖 https://github.com/theme-shoka-x/hexo-theme-shokaX/commit/ec41590c097c703fd5b54e316f7e2acb0cec02f6
此外，在一个toC项目中引入一个toB的组件库既有些奇怪，又会大大增加项目的复杂度

**Comment by Nightingale0504** [comment]
> 事实上，shokaX v0.4后已经移除了Vue的依赖 https://github.com/theme-shoka-x/hexo-theme-shokaX/commit/ec41590c097c703fd5b54e316f7e2acb0cec02f6
> 此外，在一个toC项目中引入一个toB的组件库既有些奇怪，又会大大增加项目的复杂度

好的，那我就close这个issue了
