### ISSUE TITLE
音乐盒的music和play-pause功能

### ISSUE THREAD

**Issue by yyuuz** [theme-shoka-x/hexo-theme-shokaX#315]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

无法判断

### 问题描述

![无标题](https://github.com/user-attachments/assets/0fa85b64-5ad5-41f8-b7e1-b86d0b414f3f)
点击音乐列表按钮和暂停按钮会切歌，而且是根据选择的播放顺序决定

### 复现步骤

看了其他人的博客基本都是这样

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
cc @D-Sketon

**Comment by D-Sketon** [comment]
player 部分代码过于复杂，需要梳理

**Comment by D-Sketon** [comment]
可能的修改方式
https://github.com/theme-shoka-x/hexo-theme-shokaX/blob/4adf03c6816b6196b9290928fa73973b3412f7c8/source/js/_app/player.ts#L479
true 改为 false
未严格验证

**Comment by yyuuz** [comment]
@D-Sketon 有用已解决，感谢

**Comment by zkz098** [comment]
等待相关代码修复后关闭，0.4.12发布前需保持开启状态
