### ISSUE TITLE
Code block沒有被正確的渲染

### ISSUE THREAD

**Issue by XketsuroX** [theme-shoka-x/hexo-theme-shokaX#321]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染不正确(文字undefine或空白等)

### 问题描述

這是在我網站上部署的ShokaX，他的codeblock 沒有被正確的渲染，在html裏面可以看到 class只有C++
![image](https://github.com/user-attachments/assets/dc669330-29ac-466f-aff8-2eda5a8b1cf0)
然後我在望月閣那邊查看了一段code block的element 然後把他複製過來，嗯.... 沒有問題 渲染出來是正常的code block
這裏是兩邊的對比
![image](https://github.com/user-attachments/assets/e54ba62a-22a9-405f-b9d9-fba5542fd8d8)
同樣quiz 跟 furigana的markdown 格式也不會被正常的渲染
我這邊也把我的config也post出來
https://cloud.ketsuromoe.win/s/K4SQ

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
是否是使用标签插件编写的代码块？

**Comment by XketsuroX** [comment]
> 是否是使用标签插件编写的代码块？

是的，并且我同時用了標簽插件還有markdown 語法中的代碼塊，出來的效果都是一樣。

**Comment by D-Sketon** [comment]
能否贴出package.json

**Comment by XketsuroX** [comment]
> 能否贴出package.json

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.3.0"
  },
  "dependencies": {
    "hexo": "^7.3.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-admin": "^2.3.0",
    "hexo-auto-category": "^0.2.2",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^4.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.3.0",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-theme-shokax": "^0.4.11",
    "hexo-word-counter": "^0.2.0",
    "live2d-widget-model-koharu": "^1.0.5"
  }
}
```

**Comment by D-Sketon** [comment]
请卸载hexo-renderer-marked并安装    hexo-renderer-multi-next-markdown-it

**Comment by XketsuroX** [comment]
> 请卸载hexo-renderer-marked并安装 hexo-renderer-multi-next-markdown-it

照做了，現在furigana 跟quiz這些插件沒問題了 但代碼塊依然一樣

**Comment by jootiny** [comment]
https://docs-hexo.shokax.top/getting-started/#%E6%8E%A8%E8%8D%90%E9%85%8D%E7%BD%AE

**Comment by zkz098** [comment]
> > 请卸载hexo-renderer-marked并安装 hexo-renderer-multi-next-markdown-it
> 
> 照做了，現在furigana 跟quiz這些插件沒問題了 但代碼塊依然一樣

换个语言试试，例如改成raw或者javascript，C++代码块用的是`c++`还是`cpp`

试完之后先`hexo cl`再`hexo g`

**Comment by XketsuroX** [comment]
哦哦 重啓docker后就沒問題了，話説這個的原因是什麽？npm包安裝的問題嗎
