### ISSUE TITLE
hexo g报错"_cover_index is not a function"

### ISSUE THREAD

**Issue by jootiny** [theme-shoka-x/hexo-theme-shokaX#333]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

我采用的是[git方式](https://docs-hexo.shokax.top/getting-started/#%E5%AE%89%E8%A3%85-shokax)安装的shokax，依据这些步骤后运行hexo g然后报错了。
![image](https://github.com/user-attachments/assets/21233e7f-383c-4186-b7e2-ab8cb3fa876b)
![image](https://github.com/user-attachments/assets/7279e7d7-6c36-48af-8c0a-77d9bd205d77)
![image](https://github.com/user-attachments/assets/5bf3e223-42e9-4e40-ab59-4860dc5ee8be)
是依赖的问题吗

### 复现步骤

hexo g & hexo s

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
#320

**Comment by jootiny** [comment]
感谢，已经成功用其他推荐的构建方法了
