### ISSUE TITLE
md文章小标题无法正常渲染问题

### ISSUE THREAD

**Issue by jongsh** [theme-shoka-x/hexo-theme-shokaX#337]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

不清楚是哪里出的问题，我在尝试渲染博客文档时，发现如果小标题(如二级标题、三级标题)数字开头时，文章右边的目录就无法正常加载，并且评论区也显示不出来。
所以想问问是否markdown渲染是标题不允许数字开头？

### 复现步骤

这是使用英文标题
![image](https://github.com/user-attachments/assets/c2998f4d-84be-4e90-b1ee-06bf1e7f607f)
![image](https://github.com/user-attachments/assets/4f705c33-6e97-462c-8cd9-a0cbcdf1d438)
使用数字开头标题
![image](https://github.com/user-attachments/assets/4d7a2a61-ea9a-4c54-a75f-30dbde2bc79b)
![image](https://github.com/user-attachments/assets/3ffa9ced-46eb-4fd2-8261-8c423a4137e4)

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
#322

**Comment by jongsh** [comment]
好的，感谢回复
