### ISSUE TITLE
部分文章图片不显示

### ISSUE THREAD

**Issue by couse1989** [theme-shoka-x/hexo-theme-shokaX#345]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

部分文章的图片不显示，图片路径是正常的，查看图片元素代码为
``` shell
<img loading="lazy" data-src="/images/pasted-1321.png" alt="upload successful">
```
通过浏览器开发者工具将“data-src”更改成“src”图片即可正常显示，但是我看了其它能够正常显示的文章图片元素也是`data-src`，就很奇怪，请问这个是什么原因？

### 相关配置

``` shell
bob@debian:~/Documents/shokax-can$ hexo -v
INFO  Validating config
hexo: 7.3.0
hexo-cli: 4.3.2
os: linux 6.1.0-25-amd64 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
node: 20.17.0
acorn: 8.11.3
ada: 2.9.0
ares: 1.32.3
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.1.0
openssl: 3.0.13+quic
simdutf: 5.3.0
tz: 2024a
undici: 6.19.2
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.21
v8: 11.3.244.8-node.23
zlib: 1.3.0.1-motley-209717d
```

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
给个文章链接
初步怀疑图片插入过晚没触发unlazy

**Comment by couse1989** [comment]
> 给个文章链接 初步怀疑图片插入过晚没触发unlazy
感谢你的回复，但是我现在复现不了这个问题，我印象中修改了post.pug和post.js文件，将data-src更改成src,现在生成的图片链接都是src,目前是能够正常显示图片的，我将post.pug和post.js这两个文件更改回data-src,重新生成静态文件图片链接还是src，我不记得当时是否还更改过其他什么地方了

**Comment by sugarcanecat** [comment]
@zkz098 
我目前也出现这个问题，不太清除是哪里操作问题，写文章操作和之前一样，但是部署后，该文章图片无法显示出来。
之前使用的图床：postimage，
出现问题后换成的图床：ImagHub，依旧无法显示
出现问题文章：[https://www.sugarcanecat.cn/2024/10/19/%E5%AE%89%E6%81%92%E6%9D%AF/2024%E5%B9%B4%E2%80%9C%E5%AE%89%E6%81%92%E6%9D%AF%E2%80%9D/](url)

![issue](https://github.com/user-attachments/assets/7948d85c-00b8-4608-9e57-0dd980b57bf6)

**Comment by sugarcanecat** [comment]
> @zkz098 我目前也出现这个问题，不太清除是哪里操作问题，写文章操作和之前一样，但是部署后，该文章图片无法显示出来。 之前使用的图床：postimage， 出现问题后换成的图床：ImagHub，依旧无法显示 出现问题文章：https://www.sugarcanecat.cn/2024/10/19/%E5%AE%89%E6%81%92%E6%9D%AF/2024%E5%B9%B4%E2%80%9C%E5%AE%89%E6%81%92%E6%9D%AF%E2%80%9D/
> 
> ![issue](https://private-user-images.githubusercontent.com/127029811/378715990-7948d85c-00b8-4608-9e57-0dd980b57bf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODA0MzQsIm5iZiI6MTcyOTU4MDEzNCwicGF0aCI6Ii8xMjcwMjk4MTEvMzc4NzE1OTkwLTc5NDhkODVjLTAwYjgtNDYwOC05ZTU3LTBkZDk4MGI1N2JmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNjU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWVkOTA0YWMxZDRjNDE5ZmNiODNhNGEyNjAwMTJmNTRhNTc4Mzk4ZWIzOWIwMjJjYmFiOGYxNWQxNWFkMGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vM2NmJV7pu5bBFBcrPBek-KeOodw8zKWg1gjNpHwvnE)

**Comment by sugarcanecat** [comment]
> > @zkz098 我目前也出现这个问题，不太清除是哪里操作问题，写文章操作和之前一样，但是部署后，该文章图片无法显示出来。 
之前使用的图床：postimage， 
出现问题后换成的图床：ImagHub，依旧无法显示 
出现问题文章：https://www.sugarcanecat.cn/2024/10/19/%E5%AE%89%E6%81%92%E6%9D%AF/2024%E5%B9%B4%E2%80%9C%E5%AE%89%E6%81%92%E6%9D%AF%E2%80%9D/
> > ![issue](https://private-user-images.githubusercontent.com/127029811/378715990-7948d85c-00b8-4608-9e57-0dd980b57bf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODA0MzQsIm5iZiI6MTcyOTU4MDEzNCwicGF0aCI6Ii8xMjcwMjk4MTEvMzc4NzE1OTkwLTc5NDhkODVjLTAwYjgtNDYwOC05ZTU3LTBkZDk4MGI1N2JmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNjU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWVkOTA0YWMxZDRjNDE5ZmNiODNhNGEyNjAwMTJmNTRhNTc4Mzk4ZWIzOWIwMjJjYmFiOGYxNWQxNWFkMGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vM2NmJV7pu5bBFBcrPBek-KeOodw8zKWg1gjNpHwvnE)
