### ISSUE TITLE
请适配cloudflare Rocket Loader™

### ISSUE THREAD

**Issue by MisakaMikoto521** [theme-shoka-x/hexo-theme-shokaX#346]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

请适配cloudflare Rocket Loader™
记得以前版本修复过这个问题，不过更新到最新版又复现了这个问题
确实会在解决新bug的同时，引入原有bug（狗头保命👀）

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
问题在于 rocket 的兼容代码一直没变过（
在控制台里手动运行`window.dispatchEvent(new Event('DOMContentLoaded'))`后会解决吗

**Comment by MisakaMikoto521** [comment]
> 问题在于 rocket 的兼容代码一直没变过（ 在控制台里手动运行`window.dispatchEvent(new Event('DOMContentLoaded'))`后会解决吗

会，但是也会报错

window.dispatchEvent(new Event('DOMContentLoaded'))
about/:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at bk.zaraz.init (about/:1:4026)
    at c (VM659 rocket-loader.min.js:1:9405)
    at <anonymous>:1:8
bk.zaraz.init @ about/:1
c @ VM659 rocket-loader.min.js:1
(anonymous) @ VM747:1
true

**Comment by MisakaMikoto521** [comment]
> 问题在于 rocket 的兼容代码一直没变过（ 在控制台里手动运行`window.dispatchEvent(new Event('DOMContentLoaded'))`后会解决吗

确实是运行就解决了，但是印象中感觉和cloudflare Rocket Loader™ 的兼容性似乎一直不太好（）

**Comment by zkz098** [comment]
> > 问题在于 rocket 的兼容代码一直没变过（ 在控制台里手动运行`window.dispatchEvent(new Event('DOMContentLoaded'))`后会解决吗
> 
> 确实是运行就解决了，但是印象中感觉和cloudflare Rocket Loader™ 的兼容性似乎一直不太好（）

Rocket 会把 ShokaX SiteInit 用的事件吞掉，后期重发事件时机肯定会变，难免会出点兼容性问题
根据那个报错信息像 Rocket 自身的问题，很奇怪（

**Comment by zkz098** [comment]
我已经理解了（
ShokaX ESM 模块化之后相关兼容代码会被浏览器推迟到`load`后执行，所以兼容代码执行时已经没用了
把兼容代码独立一个IIFE出来理论上就能解决

**Comment by MisakaMikoto521** [comment]
> 我已经理解了（ ShokaX ESM 模块化之后相关兼容代码会被浏览器推迟到`load`后执行，所以兼容代码执行时已经没用了 把兼容代码独立一个IIFE出来理论上就能解决

这个下一次版本升级的时候会并入吗👀

**Comment by zkz098** [comment]
> > 我已经理解了（ ShokaX ESM 模块化之后相关兼容代码会被浏览器推迟到`load`后执行，所以兼容代码执行时已经没用了 把兼容代码独立一个IIFE出来理论上就能解决
> 
> 这个下一次版本升级的时候会并入吗👀

需要验证补丁是不是真的有效

**Comment by zkz098** [comment]
0.4.16理论上修好了
