### ISSUE TITLE
兼容algolia v5

### ISSUE THREAD

**Issue by kuiyr0810** [theme-shoka-x/hexo-theme-shokaX#347]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

其他问题

### 问题描述

X [ERROR] Could not resolve "algoliasearch/dist/algoliasearch-lite.esm.browser.js" (originally "algoliasearch/lite")

    node_modules/hexo-theme-shokax/source/js/_app/page/search.ts:7:26:
      7 │ import algoliasearch from 'algoliasearch/lite'
        ╵                           ~~~~~~~~~~~~~~~~~~~~

  The path "./dist/algoliasearch-lite.esm.browser.js" is not exported by package "algoliasearch":

    node_modules/algoliasearch/package.json:18:13:
      18 │   "exports": {
         ╵              ^

  The path "algoliasearch/lite" was remapped to "algoliasearch/dist/algoliasearch-lite.esm.browser.js" using the alias feature, which then couldn't be resolved. Keep in mind that import path aliases are resolved in the current working directory.

  You can mark the path "algoliasearch/dist/algoliasearch-lite.esm.browser.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Build failed with 1 error:
node_modules/hexo-theme-shokax/source/js/_app/page/search.ts:7:26: ERROR: Could not resolve "algoliasearch/dist/algoliasearch-lite.esm.browser.js" (originally "algoliasearch/lite")
    at failureErrorWithLog (D:\blog\node_modules\esbuild\lib\main.js:1476:15)
    at D:\blog\node_modules\esbuild\lib\main.js:945:25
    at D:\blog\node_modules\esbuild\lib\main.js:897:52
    at buildResponseToResult (D:\blog\node_modules\esbuild\lib\main.js:943:7)
    at D:\blog\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (D:\blog\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (D:\blog\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (D:\blog\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)

### 复现步骤

更新了package.json中的所有

### 注意事项

- [X] 我已确认以上事项

**Comment by kuiyr0810** [comment]
已解决，algoliasearch版本问题，降级即可

**Comment by zkz098** [comment]
搜索跨大版本升级兼容性问题，修复前保持开启

**Comment by zkz098** [comment]
cc @D-Sketon @FidStyle 
测一下 https://github.com/theme-shoka-x/hexo-theme-shokaX/commit/1b4ee209e5befe5b9a3d921724fbc5383003234f 改完的版本搜索能不能正常使用
我这边打包一直在引入algoliaseach@4的js，怀疑打包环境被污染了

**Comment by D-Sketon** [comment]
没有问题
