### ISSUE TITLE
建议使用 CDN 引入 Twikoo 的用户在代码中加入 SRI 以确保完整性

### ISSUE THREAD

**Issue by MisakaMikoto521** [theme-shoka-x/hexo-theme-shokaX#351]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 建议描述

摘自twikoo官网，不知道本主题是否在评论系统增加类似的安全性措施防止供应链攻击。虽然记得以前更新过SRI机制，但是不知道评论这里是否有引入👀

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
twikoo和waline走的是本地Bundle，CDN配置属于历史遗留问题，无需配置SRI
