### ISSUE TITLE
关于Prism代码高亮

### ISSUE THREAD

**Issue by departever** [theme-shoka-x/hexo-theme-shokaX#353]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

将syntax_highlighter: false设置完之后仍然出现这个报错：prism's diff highlight plugin requires the diff language definition (prism-diff.js).make sure the language definition is loaded or use prism's autoloader plugin.

### 复现步骤

就是在hexo g的时候报错这个。试了好多次也是这样，跪求大佬解答👀

### 相关配置

我在_config.yml中配置如下：
syntax_highlighter: false
highlight:
  enable: false
prismjs:
  enable: false

环境hexo: 7.3.0
hexo-cli: 4.3.2
os: win32 10.0.22631 undefined
node: 20.15.1
acorn: 8.11.3
ada: 2.7.8
ares: 1.28.1
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.1.0
openssl: 3.0.13+quic
simdutf: 5.2.8
tz: 2024a
undici: 6.13.0
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.21
v8: 11.3.244.8-node.23
zlib: 1.3.0.1-motley-7d77fb7

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
只是警告，无需在意

**Comment by departever** [comment]
哈哈哈行，感谢。其实之前用hexo的时候也有时候遇到这个问题，之前下了prismjs把node_moudles里那个换了就没这个问题了。但是部署到vercel上也不可能把这个换了的文件传上去😎
