### ISSUE TITLE
部分图片无法显示

### ISSUE THREAD

**Issue by sugarcanecat** [theme-shoka-x/hexo-theme-shokaX#358]
我目前出现这个问题，不太清除是哪里操作问题，写文章操作和之前一样，但是部署后，该文章图片无法显示出来。 
之前使用的图床：postimage， 
出现问题后换成的图床：ImagHub，依旧无法显示 
出现问题文章：https://www.sugarcanecat.cn/2024/10/19/%E5%AE%89%E6%81%92%E6%9D%AF/2024%E5%B9%B4%E2%80%9C%E5%AE%89%E6%81%92%E6%9D%AF%E2%80%9D/
> > ![issue](https://private-user-images.githubusercontent.com/127029811/378715990-7948d85c-00b8-4608-9e57-0dd980b57bf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODA0MzQsIm5iZiI6MTcyOTU4MDEzNCwicGF0aCI6Ii8xMjcwMjk4MTEvMzc4NzE1OTkwLTc5NDhkODVjLTAwYjgtNDYwOC05ZTU3LTBkZDk4MGI1N2JmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNjU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWVkOTA0YWMxZDRjNDE5ZmNiODNhNGEyNjAwMTJmNTRhNTc4Mzk4ZWIzOWIwMjJjYmFiOGYxNWQxNWFkMGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vM2NmJV7pu5bBFBcrPBek-KeOodw8zKWg1gjNpHwvnE)

_最初由 @sugarcanecat 在 https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/345#issuecomment-2428408844 发布_

**Comment by D-Sketon** [comment]
请升级到最新版本，你的博客有#322 报错

**Comment by sugarcanecat** [comment]
> 请升级到最新版本，你的博客有#322 报错

感谢🙏
