### ISSUE TITLE
本地部署测试的时候提示[cause]: Error: read ECONNRESET

### ISSUE THREAD

**Issue by hmilyoux** [theme-shoka-x/hexo-theme-shokaX#376]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [X] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

无法判断

### 问题描述
![image](https://github.com/user-attachments/assets/2646ff94-43d1-4ac8-be18-39d50879dbf1)

F:\blog-shokax\hzctst>hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
node:internal/deps/undici/undici:13484
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

Node.js v23.5.0

### 复现步骤

正常按照教程部署，在最后hexo s的时候出现这个报错。在Google搜索多次没有找到解决办法，请求各位大牛支个招！
测试过14.0.0版本的nodejs不会报这个错，但是会提示其他语法错误。

### 相关配置

环境配置如下：

hexo: 7.3.0
hexo-cli: 4.3.2
os: win32 10.0.19045 undefined
node: 23.5.0
acorn: 8.14.0
ada: 2.9.2
amaro: 0.2.0
ares: 1.34.4
brotli: 1.1.0
cjs_module_lexer: 1.4.1
cldr: 46.0
icu: 76.1
llhttp: 9.2.1
modules: 131
napi: 9
nbytes: 0.1.1
ncrypto: 0.0.1
nghttp2: 1.64.0
nghttp3: 1.6.0
ngtcp2: 1.9.1
openssl: 3.0.15+quic
simdjson: 3.10.1
simdutf: 5.6.4
sqlite: 3.47.2
tz: 2024b
undici: 6.21.0
unicode: 16.0
uv: 1.49.2
uvwasi: 0.0.21
v8: 12.9.202.28-node.12
zlib: 1.3.0.1-motley-82a5fec

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
14版本node不报错是因为版本太老根本就启动不了。。。
优先检查存不存在其他插件需要使用网络，ShokaX的网络有关请求基本都做了错误处理，但近期API连通性极差，不排除网络问题

**Comment by zkz098** [comment]
0.4.17版本停用了API，更新试试

**Comment by hmilyoux** [comment]
> 0.4.17版本停用了API，更新试试

谢谢！！更新之后的版本确实没问题了！部署到git的时候会有提示“sinaimg blocked all request from outside website,so don't use this format”，没找到这个是哪里发出的提示
![image](https://github.com/user-attachments/assets/640b5366-fdcd-4470-85a2-1d4cc64445ea)

**Comment by zkz098** [comment]
在images.yml中使用新浪图床就会出现这个提示，参考 #6 自行部署图床即可

**Comment by chxcodepro** [comment]
> 0.4.17版本停用了API，更新试试

作者能更新一下https://github.com/theme-shoka-x/shokax-can 即食罐头吗，这个版本也启动不了了
