### ISSUE TITLE
删除一些不必要的polyfill和代码

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#52]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

ShokaX已经终止了对于某些EOL浏览器(例如IE11)的支持，但仍然因历史问题保留了大量兼容IE11的polyfill(例如whatwg-fetch和polyfill-service)
目前需要通过删除(或改为可选)等方式处理掉这些polyfill以提高在现代浏览器上的性能
同时，ShokaX使用的部分依赖库(例如Pjax和anime)已经长时间未更新，需要考虑寻找替代方案。对hexo-script部分的重构也需要提上日程，这部分代码使用了一些废弃模块并且代码难以理解。
最后，应考虑全NPM化的可行性，即取消git clone方式安装，仅保留发行版zip和npm方式安装；移除掉github仓库内的js编译版，仅保留ts文件，将js编译交给CI去做

(此issues仅为草稿，功能可能不会全部实现)

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
pjax有什么替代品吗

**Comment by zkz098** [comment]
> pjax有什么替代品吗

目前没发现，也许可以换成更可控和积极维护的Pjax

**Comment by D-Sketon** [comment]
要不自己手写一个吧（）

**Comment by zkz098** [comment]
> 要不自己手写一个吧（），这样还能减少点代码体积

可以和next-theme一样，把现在的这个Pjax改改做个精简版，删掉shokaX用不到的部分

**Comment by D-Sketon** [comment]
> > 要不自己手写一个吧（），这样还能减少点代码体积
> 
> 可以和next-theme一样，把现在的这个Pjax改改做个精简版，删掉shokaX用不到的部分

anime也是，完全可以精简

**Comment by zkz098** [comment]
图片懒加载可以考虑更换为使用原生的懒加载
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/39bc7394-d8c0-43fc-a3ab-817e1a763268)
兼容性: https://caniuse.com/loading-lazy-attr
基本上可以兼容93%的用户浏览器

**Comment by D-Sketon** [comment]
> 图片懒加载可以考虑更换为使用原生的懒加载 ![image](https://user-images.githubusercontent.com/92242020/243164346-39bc7394-d8c0-43fc-a3ab-817e1a763268.png) 兼容性: https://caniuse.com/loading-lazy-attr 基本上可以兼容93%的用户浏览器 图片decode也可考虑更换为异步(针对非关键图片)

loading="lazy"和lozad.js效果也许会不一样，且存在一些缺点
[图片懒加载不完全指南](https://zhuanlan.zhihu.com/p/423328031)

**Comment by zkz098** [comment]
是否有必要迁移到 https://unlazy.byjohann.dev/，即使用unlazy取代lozad，这个更现代。
可能需要loading="lazy"
@D-Sketon

**Comment by zkz098** [comment]
可能需要引入一个后优化插件解决 css 未使用部分

**Comment by zkz098** [comment]
这个任务交给astro迁移
