### ISSUE TITLE
cdn.jsdelivr.net 不可用

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#58]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

![image](https://user-images.githubusercontent.com/49871906/230333651-cee24462-7b52-4fbe-8841-f3b4a6725558.png)
不知何时恢复

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
![image](https://user-images.githubusercontent.com/92242020/230392703-5d77d4ce-5932-4956-910a-54c21e08a247.png)
没有观察到明显的DNS污染或阻断现象
这个超时应该是Fastly不定期抽风()，近几天如果都这样就大概率是寄了

**Comment by zkz098** [comment]
![image](https://user-images.githubusercontent.com/92242020/230610604-1295e1f9-60c7-4e2c-a0f0-bc40ab805bb6.png)
失败原因主要还是超时，应该没有被阻断()
但这个离谱的网络质量也需要关注，现在shoka(没有X)的网站基本上加载都是5分钟起步

**Comment by zkz098** [comment]
目前jsd还是基本可用的
先关了，后续有问题再打开()
