### ISSUE TITLE
优化国际化翻译

### ISSUE THREAD

**Issue by zkz098** [theme-shoka-x/hexo-theme-shokaX#75]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

目前语言文件极度混乱，繁体中文缺本地化键，英语不符合口语习惯等问题大量存在
在0.3版本会集中整理语言文件并考虑重构国际化代码(现行代码仅支持四种语言)

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
建议增加英语文档

**Comment by zkz098** [comment]
英文文档翻译正在稳步进行，完成度已达70%

**Comment by TKanX** [comment]
如果有需要我可以帮助完成英文文档翻译工作。

**Comment by zkz098** [comment]
> 如果有需要我可以帮助完成英文文档翻译工作。

需要的，已发送invitation，接受后可获得成员权限

**Comment by TKanX** [comment]
谢邀，已进

**Comment by TKanX** [comment]
包含中文图片的英文文档怎么处理？

**Comment by zkz098** [comment]
> 包含中文图片的英文文档怎么处理？

可以删除中文图片和相关描述

**Comment by zkz098** [comment]
任务阶段性完成
