### ISSUE TITLE
代码模块化

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/hexo-theme-shokaX#81]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
- [X] 我确认最新版尚未添加此功能，且此前没有人提出过此问题

### 建议描述

是否有必要将 `source/js/_app` 下的代码使用ESM重新模块化？现在调试起来有点困难，而且ts的使用体验也很糟糕😫

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
有必要，现在hexo script和source js的函数都是乱的，文件也没有明确从属关系
应该需要配合一个打包器，把script.ts的任务交给ci去做，否则ESM直接从浏览器端导入的话兼容性略差(Chrome ≤66这个也算老浏览器了，直接浏览器端引入ESM应该也行)

**Comment by D-Sketon** [comment]
> 有必要，现在hexo script和source js的函数都是乱的，文件也没有明确从属关系
> 应该需要配合一个打包器，把script.ts的任务交给ci去做，否则ESM直接从浏览器端导入的话兼容性略差(Chrome ≤66这个也算老浏览器了，直接浏览器端引入ESM应该也行)

ESM直接使用rollup打包挺好的()

**Comment by zkz098** [comment]
> ESM直接使用rollup打包挺好的()

是这样的()

直接让CI一站式服务，渲染器的terser都省了()

**Comment by D-Sketon** [comment]
有点抽象，源代码用了大量的全局变量，改起来有点麻烦

**Comment by zkz098** [comment]
> 有点抽象，源代码用了大量的全局变量，改起来有点麻烦

Library.ts 中的 object.assign 也相当抽象，ts无法识别并且需要3-6秒才能执行完成
是否可以考虑做成一个HTMLelement的派生类并和$dom结合，这样ts可以识别，运行速度也能快不少

**Comment by D-Sketon** [comment]
比较麻烦的是如何才能按需加载fireworks和player，之前是直接采用拼接js文件的方式

**Comment by zkz098** [comment]
> 比较麻烦的是如何才能按需加载fireworks和player，之前是直接采用拼接js文件的方式 直接用esm的动态导入吗?

可以作为一种方案，ESM支持已经不算差了。
另一种方案就是让SXC现场打包，直接`SXC rebuild`

**Comment by zkz098** [comment]
> 可以作为一种方案，ESM支持已经不算差了。 另一种方案就是让SXC现场打包，直接`SXC rebuild`

另外就是先别改source js，我正在重构library，两边一块改容易冲突()

**Comment by D-Sketon** [comment]
> > 可以作为一种方案，ESM支持已经不算差了。 另一种方案就是让SXC现场打包，直接`SXC rebuild`
> 
> 另外就是先别改source js，我正在重构library，两边一块改容易冲突()

坏了，我都快改完了（）

**Comment by zkz098** [comment]
> > > 可以作为一种方案，ESM支持已经不算差了。 另一种方案就是让SXC现场打包，直接`SXC rebuild`
> > 
> > 
> > 另外就是先别改source js，我正在重构library，两边一块改容易冲突()
> 
> 坏了，我都快改完了（）

寄
你先发PR，我看看改的部分重没重复()

**Comment by D-Sketon** [comment]
> > > > 可以作为一种方案，ESM支持已经不算差了。 另一种方案就是让SXC现场打包，直接`SXC rebuild`
> > > 
> > > 
> > > 另外就是先别改source js，我正在重构library，两边一块改容易冲突()
> > 
> > 坏了，我都快改完了（）
> 
> 寄
> 你先发PR，我看看改的部分重没重复()

没事，我这个算大改，估计要开个分支，到时候我肉眼merge一下（）

**Comment by zkz098** [comment]
现在dom工具类的修改进入了一个奇怪的循环：
解决Typescript不识别和效率问题，把Object.assign修改为装饰类+proxy
但是Typescript也不识别proxy，需要直接访问装饰类绑定的节点
但这样的话装饰类就没用了，直接proxy就能解决
但Typescript不识别proxy，所以改了个寂寞

**Comment by zkz098** [comment]
> 现在dom工具类的修改进入了一个奇怪的循环： 解决Typescript不识别和效率问题，把Object.assign修改为装饰类+proxy 但是Typescript也不识别proxy，需要直接访问装饰类绑定的节点 但这样的话装饰类就没用了，直接proxy就能解决 但Typescript不识别proxy，所以改了个寂寞

用了一些奇怪的方法，但现在typescript可以识别proxy了()

**Comment by zkz098** [comment]
还是直接注入原型舒服，不改dom工具类了()

**Comment by zkz098** [comment]
> 没事，我这个算大改，估计要开个分支，到时候我肉眼merge一下（）

目前进度如何，如果差不多我就提前改改CLI（）

**Comment by D-Sketon** [comment]
> > 没事，我这个算大改，估计要开个分支，到时候我肉眼merge一下（）
> 
> 目前进度如何，如果差不多我就提前改改CLI（）
> 

非常缓慢，改了跑不起来了()

**Comment by D-Sketon** [comment]
目前的问题主要在动态引入后造成的分包会被多次调用，造成报错👀

**Comment by zkz098** [comment]
关于功能禁用的问题，实际上有一个过渡的解决方案: 在每次生成文件时调用esbuild API打包并输出
解决了用户需要手动rebuild或ESM动态导入的问题
esbuild的性能比rollup要好，少的功能这种情况下也用不上
但缺点也有不少:
- 生成静态文件时明显的卡顿: 虽然esbuild的性能很高，但是ShokaX的这个代码量也是问题，所以不可能实现无感打包
- 可能导致意料之外的问题: 将打包转移到客户端会让程序面临更复杂的环境，发生任何出乎意料的事都是正常的

或许可以在0.3.x作为过渡方案加入（）

**Comment by zkz098** [comment]
是否有必要对markdown渲染器也进行模块化，即拆分为`core`、`math`、`minify`等多个分包，允许用户自由选择
这将会解决KaTeX和mathjax冲突、mermaid导致的安装失败等问题，同时降低 ShokaX 基本使用者的磁盘空间负担（

**Comment by zkz098** [comment]
https://github.com/theme-shoka-x/hexo-theme-shokaX/commit/e86819e670708d1f53b6fae1de42f5b658c55bbd 这一版本的代码模块化已在我本地通过测试，可以正常运行
由于现版本把anime、pjax和lozad这几个重要模块直接捆绑到了app.js中（便于tree-shakeing和编译期minify），所以需要额外安装对应模块和`esbuild`才能运行
得益于esbuild的优秀性能，打包近乎无感（8-10ms，和文件拼接差不多），noPlayer和fireworks禁用基于编译期死代码消除实现。

**Comment by zkz098** [comment]
渲染器模块化正在进行（）
minify功能已经被拆成了一个独立的模块，未来将不随MD渲染器发布，得益于Rust的高性能，这个版本会比之前要快不少
MD渲染器也会部分模块化，`import()`立大功（）

**Comment by zkz098** [comment]
新缩小器效率有点恐怖：
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/b3165324-681b-448a-bb8d-cb78d9d41a3c)
这数有点不敢写了（）

**Comment by D-Sketon** [comment]
with [hexo-many-posts](https://github.com/hexojs/hexo-many-posts)
||base|hexo-neat|hexo-minify|hexo-all-minifier|hexo-lightning-minify
-|-|-|-|-|-|
landscape | 10.529s | 37.918s | 36.844s | 38.572s | 16.304s 
next | 27.275s | 36.124s | 42.854s | 37.063s  | 29.880s 
butterfly | 13.853s | 26.641s | 26.736s | 35.973s | 16.796s 
particlex | 24.422s | 200.641s | 193.981s | 201.601s | 40.478s 
reimu | 17.631s | 52.432s | 48.524s | 51.835s | 23.938s 
shokax(hexo-renderer-marked) | 13.189s | 20.618s | 19.658s | 22.448s | 14.619s

**Comment by D-Sketon** [comment]
![bar-label-rotation (1)](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/49871906/b47073c1-ccd1-4461-9478-b5d2717e0ca1)

**Comment by D-Sketon** [comment]
|                              | base         | hexo-neat    | hexo-minify  | hexo-all-minifier | hexo-lightning-minify | 
 | :--------------------------- | ------------ | ------------ | ------------ | ----------------- | --------------------- | 
 | landscape                    | 99,617,529B  | 97,186,156B  | 92,010,232B  | 97,184,707B       | 88,175,339B           | 
 | next                         | 32,469,157B  | 30,087,003B  | 28,744,583B  | 30,059,443B       | 28,020,740B           | 
 | butterfly                    | 37,593,633B  | 37,237,074B  | 33,485,597B  | 34,897,171B       | 35,504,670B           | 
 | particlex                    | 540,876,348B | 226,997,833B | 214,050,994B | 226,990,791B      | 221,896,130B          | 
 | reimu                        | 110,252,086B | 95,756,049B  | 91,074,639B  | 95,715,486B       | 88,088,009B           | 
 | shokax(hexo-renderer-marked) | 142,585,026B | 142,404,138B | 140,988,094B | 142,011,849B      | 140,457,331B          | 
  
 图表中为了更加清晰的对比，所以移除了 hexo-theme-particlex 
  
 ![chart2](https://github.com/theme-shoka-x/hexo-lightning-minify/assets/49871906/4eea08d2-c51e-474b-ac16-d9e8ecb52d00)

**Comment by zkz098** [comment]
> base	hexo-neat	hexo-minify	hexo-all-minifier	hexo-lightning-minify
> landscape	99,617,529B	97,186,156B	92,010,232B	97,184,707B	88,175,339B
> next	32,469,157B	30,087,003B	28,744,583B	30,059,443B	28,020,740B
> butterfly	37,593,633B	37,237,074B	33,485,597B	34,897,171B	35,504,670B
> particlex	540,876,348B	226,997,833B	214,050,994B	226,990,791B	221,896,130B
> reimu	110,252,086B	95,756,049B	91,074,639B	95,715,486B	88,088,009B
> shokax(hexo-renderer-marked)	142,585,026B	142,404,138B	140,988,094B	142,011,849B	140,457,331B
> 图表中为了更加清晰的对比，所以移除了 hexo-theme-particlex
> 
> ![chart2](https://private-user-images.githubusercontent.com/49871906/290875534-4eea08d2-c51e-474b-ac16-d9e8ecb52d00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDIyNzQsIm5iZiI6MTcwMjcwMTk3NCwicGF0aCI6Ii80OTg3MTkwNi8yOTA4NzU1MzQtNGVlYTA4ZDItYzUxZS00NzRiLWFjMTYtZDllOGVjYjUyZDAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0NDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNGY3NWYxNTdiMzg1M2ZkOTViYzMxMTZhMzVlZTkwZjU4OWVkZDc3ZWQ5Zjc0OWRhMDMxODgwMzkwNTQwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmC3qvgPYtGEj04aBxIzldsPqsZu7hiBRizY2_5tfiI)

测试的时候开启自动 WebP 化了吗

**Comment by D-Sketon** [comment]
仅测试html、js、css的压缩

**Comment by D-Sketon** [comment]
theme-shokax-anime已ts化

**Comment by zkz098** [comment]
> firework基本抽离完毕，是否使用看具体情况

存在不能用的情况吗（）

**Comment by D-Sketon** [comment]
theme-shokax-pjax已ts化

**Comment by zkz098** [comment]
对 ESM 和 CJS 进行了拆分，现在 hexo scripts 使用 CJS，source 使用 ESM 模块
esbuild tree-shaking 现在能正常优化代码了（）
但是现版本 tsc 还是很玄学，有可能随机出现 CJS 变成 ESM 或者 target 掉到 ES5 的情况（）

**Comment by zkz098** [comment]
最终使用朴素方法解决模块混乱问题（指跑两遍tsc）

**Comment by zkz098** [comment]
新的 md 渲染器需要一个美丽的名字，现有的这个名字不能继续堆了（

**Comment by zkz098** [comment]
检查主题更新、Vendors加载和`canonical`这种通用率较高的方法有必要抽离成一个公共库吗，这些方法各个主题用的都不少而且实现基本一致

@D-Sketon

**Comment by D-Sketon** [comment]
> 检查主题更新、Vendors加载和`canonical`这种通用率较高的方法有必要抽离成一个公共库吗，这些方法各个主题用的都不少而且实现基本一致
> 
> @D-Sketon 

可以考虑

**Comment by zkz098** [comment]
虽然我不理解为什么不用`any`，但是`object`属于是给了一个重击：
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/92242020/7d4cb3d3-813a-4ffd-b663-4aab35030a25)
已经在 as any了（）

**Comment by zkz098** [comment]
ShokaX 本体拆分已基本完成，生态系统模块化归入0.4计划
