### ISSUE TITLE
关于 md 渲染时出现 Nunjucks Error

### ISSUE THREAD

**Issue by ruoxijun** [theme-shoka-x/hexo-theme-shokaX#85]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

在 md 文件代码块中存在 `{{` 和 `}}` 符号时渲染会出现如下报错：

```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Nunjucks Error: _posts/interest/云原生.md [Line 41, Column 767] unexpected token: .
    =====               Context Dump               =====
    === (line number probably different from source) ===
```

目前我已知解决方案：
1. 目前我的解决方案是在 `{{` 等中间添加空格 `{ {` 
2. hexo 官网也有提出使用 `{% raw %}  {% endraw %}` 来包裹代码块中 `{{ }}` 代码
3. 使用 `&#123` 和 `&#125` 来转义 `{` 和 `}`

以上方案都需要我改动 md 源文件这是不合理的，希望作者可以解决此问题谢谢

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
改成pug之后禁用nunjucks标签应该没有大问题，但涉及底层markdown渲染修改，可能需要一些时间

**Comment by zkz098** [comment]
这个问题和 hexo 的 tag 渲染机制存在技术上的冲突
短期内很难解决

**Comment by katelynn620** [comment]
看了一下官方API裡面可以禁用，請參考以下連結：
[禁用 Nunjucks 标签](https://hexo.io/zh-cn/api/renderer.html#%E7%A6%81%E7%94%A8-Nunjucks-%E6%A0%87%E7%AD%BE)

已經嘗試改好了，放在 https://github.com/theme-shoka-x/hexo-renderer-multi-next-markdown-it/pull/9
乍看沒問題，但可能要驗一下是否有其他side effect

**Comment by zkz098** [comment]
渲染器0.1.7版本已修复

**Comment by zkz098** [comment]
> 看了一下官方API裡面可以禁用，請參考以下連結： [禁用 Nunjucks 标签](https://hexo.io/zh-cn/api/renderer.html#%E7%A6%81%E7%94%A8-Nunjucks-%E6%A0%87%E7%AD%BE)
> 
> 已經嘗試改好了，放在 [theme-shoka-x/hexo-renderer-multi-next-markdown-it#9](https://github.com/theme-shoka-x/hexo-renderer-multi-next-markdown-it/pull/9) 乍看沒問題，但可能要驗一下是否有其他side effect

应该没有副作用

**Comment by zkz098** [comment]
由于目前的实现存在副作用，已于0.1.9(尚未发布)中移除此解决方案。

**Comment by D-Sketon** [comment]
最小的md改动方式应该就是在front-matter中设置disableNunjucks

**Comment by D-Sketon** [comment]
由于全局禁用Nunjucks会导致标签插件失效，对主题的基本渲染有影响，所以我不认为主题需要对此负责

**Comment by zkz098** [comment]
在有一个无副作用的解决方案前，主题不会对此负责，此问题更类似于 Hexo 的问题而非 ShokaX
